# Generated by Django 5.2.13 on 2026-04-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='sesso',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1),
        ),
    ]
