# Generated by Codex on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_TIPI_CONTRATTO = [
    ("tempo_indeterminato", "Tempo indeterminato"),
    ("tempo_determinato", "Tempo determinato"),
    ("apprendistato", "Apprendistato"),
    ("collaborazione", "Collaborazione"),
    ("stage", "Stage / tirocinio"),
    ("altro", "Altro"),
]


def crea_tipi_e_collega_contratti(apps, schema_editor):
    TipoContrattoDipendente = apps.get_model("gestione_amministrativa", "TipoContrattoDipendente")
    ContrattoDipendente = apps.get_model("gestione_amministrativa", "ContrattoDipendente")

    tipi_by_old_value = {}
    for ordine, (old_value, nome) in enumerate(DEFAULT_TIPI_CONTRATTO, start=10):
        tipo, _ = TipoContrattoDipendente.objects.get_or_create(
            nome=nome,
            defaults={
                "ordine": ordine,
                "attivo": True,
                "note": "",
            },
        )
        tipi_by_old_value[old_value] = tipo

    fallback = tipi_by_old_value.get("tempo_indeterminato") or next(iter(tipi_by_old_value.values()), None)
    for contratto in ContrattoDipendente.objects.all():
        tipo = tipi_by_old_value.get(contratto.tipo_contratto) or fallback
        if tipo:
            contratto.tipo_contratto_fk_id = tipo.pk
            contratto.save(update_fields=["tipo_contratto_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("gestione_amministrativa", "0002_dipendente_sesso"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoContrattoDipendente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("ordine", models.IntegerField(blank=True, null=True)),
                ("attivo", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo contratto dipendente",
                "verbose_name_plural": "Tipi contratto dipendente",
                "db_table": "gestione_amministrativa_tipo_contratto_dipendente",
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.AddField(
            model_name="dipendente",
            name="tipo_contratto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dipendenti",
                to="gestione_amministrativa.tipocontrattodipendente",
            ),
        ),
        migrations.AddField(
            model_name="contrattodipendente",
            name="tipo_contratto_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="gestione_amministrativa.tipocontrattodipendente",
            ),
        ),
        migrations.RunPython(crea_tipi_e_collega_contratti, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="contrattodipendente",
            name="tipo_contratto",
        ),
        migrations.RenameField(
            model_name="contrattodipendente",
            old_name="tipo_contratto_fk",
            new_name="tipo_contratto",
        ),
        migrations.AlterField(
            model_name="contrattodipendente",
            name="tipo_contratto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratti",
                to="gestione_amministrativa.tipocontrattodipendente",
            ),
        ),
    ]
