# Generated by Django 5.2.13 on 2026-05-11 00:33

import django.db.models.deletion
from django.db import migrations, models


def seed_persone_da_dipendenti(apps, schema_editor):
    Dipendente = apps.get_model("gestione_amministrativa", "Dipendente")
    Persona = apps.get_model("anagrafica", "Persona")
    Nazione = apps.get_model("anagrafica", "Nazione")
    db_alias = schema_editor.connection.alias

    for dipendente in (
        Dipendente.objects.using(db_alias)
        .select_related("familiare_collegato", "familiare_collegato__persona")
        .all()
        .iterator()
    ):
        persona_id = None
        familiare = dipendente.familiare_collegato
        if familiare and familiare.persona_id:
            persona_id = familiare.persona_id

        codice_fiscale = (dipendente.codice_fiscale or "").upper().strip()
        if not persona_id and codice_fiscale:
            persona_id = (
                Persona.objects.using(db_alias)
                .filter(codice_fiscale__iexact=codice_fiscale)
                .values_list("pk", flat=True)
                .first()
            )

        if not persona_id:
            nazionalita_id = None
            nazionalita_label = (dipendente.nazionalita or "").strip()
            if nazionalita_label:
                nazionalita_id = (
                    Nazione.objects.using(db_alias)
                    .filter(nome_nazionalita__iexact=nazionalita_label)
                    .values_list("pk", flat=True)
                    .first()
                ) or (
                    Nazione.objects.using(db_alias)
                    .filter(nome__iexact=nazionalita_label)
                    .values_list("pk", flat=True)
                    .first()
                )
            persona = Persona.objects.using(db_alias).create(
                indirizzo_id=dipendente.indirizzo_id,
                nome=dipendente.nome or "",
                cognome=dipendente.cognome or "",
                sesso=dipendente.sesso or "",
                data_nascita=dipendente.data_nascita,
                luogo_nascita_custom=dipendente.luogo_nascita or "",
                nazionalita_id=nazionalita_id,
                codice_fiscale=codice_fiscale,
                email=dipendente.email or "",
                telefono=dipendente.telefono or "",
                note=dipendente.note or "",
            )
            persona_id = persona.pk

        Dipendente.objects.using(db_alias).filter(pk=dipendente.pk).update(persona_collegata_id=persona_id)


def unseed_persone_da_dipendenti(apps, schema_editor):
    Dipendente = apps.get_model("gestione_amministrativa", "Dipendente")
    db_alias = schema_editor.connection.alias
    Dipendente.objects.using(db_alias).update(persona_collegata_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0003_persona_familiare_persona_and_more'),
        ('gestione_amministrativa', '0002_seed_payroll_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='persona_collegata',
            field=models.ForeignKey(blank=True, help_text='Anagrafica persona condivisa con familiari, educatori e dipendenti.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profili_lavorativi', to='anagrafica.persona'),
        ),
        migrations.RunPython(seed_persone_da_dipendenti, unseed_persone_da_dipendenti),
    ]
