# Generated by Django 5.2.13 on 2026-04-24 11:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0003_tipo_contratto_dipendente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='tipo_contratto',
        ),
        migrations.AddField(
            model_name='contrattodipendente',
            name='parametro_calcolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratti', to='gestione_amministrativa.parametrocalcolostipendio'),
        ),
        migrations.AddField(
            model_name='contrattodipendente',
            name='tariffa_oraria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='contrattodipendente',
            name='dipendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratti', to='gestione_amministrativa.dipendente'),
        ),
    ]
