# Generated by Django 5.2.13 on 2026-05-11 00:52

from django.db import migrations, models


def normalizza_ruolo_aziendale(apps, schema_editor):
    Dipendente = apps.get_model("gestione_amministrativa", "Dipendente")
    db_alias = schema_editor.connection.alias
    Dipendente.objects.using(db_alias).filter(ruolo_aziendale="educatore_dipendente").update(
        ruolo_aziendale="educatore"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0003_dipendente_persona_collegata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bustapagadipendente',
            options={'ordering': ['-anno', '-mese', 'dipendente__persona_collegata__cognome', 'dipendente__persona_collegata__nome'], 'verbose_name': 'Busta paga dipendente', 'verbose_name_plural': 'Buste paga dipendenti'},
        ),
        migrations.AlterModelOptions(
            name='contrattodipendente',
            options={'ordering': ['dipendente__persona_collegata__cognome', 'dipendente__persona_collegata__nome', '-data_inizio'], 'verbose_name': 'Contratto dipendente', 'verbose_name_plural': 'Contratti dipendenti'},
        ),
        migrations.AlterModelOptions(
            name='dipendente',
            options={'ordering': ['persona_collegata__cognome', 'persona_collegata__nome'], 'verbose_name': 'Dipendente', 'verbose_name_plural': 'Dipendenti'},
        ),
        migrations.AlterModelOptions(
            name='documentodipendente',
            options={'ordering': ['dipendente__persona_collegata__cognome', 'dipendente__persona_collegata__nome', '-data_documento', '-id'], 'verbose_name': 'Documento dipendente', 'verbose_name_plural': 'Documenti dipendenti'},
        ),
        migrations.RemoveConstraint(
            model_name='dipendente',
            name='ga_dip_cod_unique',
        ),
        migrations.RemoveConstraint(
            model_name='dipendente',
            name='ga_dip_cf_unique',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='codice_dipendente',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='codice_fiscale',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='data_nascita',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='familiare_collegato',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='indirizzo',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='luogo_nascita',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='nazionalita',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='nome',
        ),
        migrations.RenameField(
            model_name='dipendente',
            old_name='ruolo_anagrafico',
            new_name='ruolo_aziendale',
        ),
        migrations.RunPython(normalizza_ruolo_aziendale, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dipendente',
            name='ruolo_aziendale',
            field=models.CharField(choices=[('dipendente', 'Dipendente'), ('educatore', 'Educatore')], db_index=True, default='dipendente', max_length=30),
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='sesso',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='telefono',
        ),
    ]
