# Generated by Django 5.2.13 on 2026-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0004_remove_dipendente_tipo_contratto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrattodipendente',
            name='regime_orario',
            field=models.CharField(choices=[('tempo_pieno', 'Tempo pieno'), ('tempo_parziale', 'Part-time')], default='tempo_pieno', max_length=30),
        ),
    ]
