# Generated by Django 5.2.13 on 2026-05-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0004_alter_bustapagadipendente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dipendente',
            name='data_assunzione',
        ),
        migrations.RemoveField(
            model_name='dipendente',
            name='data_cessazione',
        ),
    ]
