# Generated by Django 5.2.13 on 2026-04-28 18:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0005_alter_contrattodipendente_regime_orario'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulazioneCostoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=180)),
                ('data_elaborazione', models.DateField(blank=True, null=True)),
                ('valido_dal', models.DateField()),
                ('valido_al', models.DateField(blank=True, null=True)),
                ('netto_mensile', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lordo_mensile', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_azienda_mensile', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contributi_previdenziali_azienda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contributi_assicurativi_azienda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contributi_previdenza_complementare_azienda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contributi_previdenziali_dipendente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contributi_assicurativi_dipendente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('contributi_previdenza_complementare_dipendente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('irpef_lorda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('irpef_netto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('addizionale_regionale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('addizionale_comunale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bonus_fiscali', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('trattamento_fine_rapporto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_mensilita_aggiuntive', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_rateo_ferie', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_rateo_permessi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_rateo_rol', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_rateo_ex_festivita', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mensilita_annue', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('ore_mensili', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('giorni_mensili', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('percentuale_part_time', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tasso_inail_per_mille', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('livello', models.CharField(blank=True, max_length=60)),
                ('qualifica', models.CharField(blank=True, max_length=120)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('file_simulazione', models.FileField(blank=True, upload_to='gestione_amministrativa/simulazioni_costo/%Y/%m')),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulazioni_costo', to='gestione_amministrativa.contrattodipendente')),
            ],
            options={
                'verbose_name': 'Simulazione costo dipendente',
                'verbose_name_plural': 'Simulazioni costo dipendenti',
                'db_table': 'gestione_amministrativa_simulazione_costo_dipendente',
                'ordering': ['contratto', '-valido_dal', '-id'],
                'indexes': [models.Index(fields=['contratto', 'valido_dal'], name='ga_sim_costo_contr_idx'), models.Index(fields=['attiva'], name='ga_sim_costo_attiva_idx')],
            },
        ),
    ]
