# Generated by Django 5.2.13 on 2026-05-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0005_remove_dipendente_data_assunzione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='materia',
            field=models.CharField(blank=True, help_text='Materia di riferimento per educatori trasversali a piu classi.', max_length=120),
        ),
    ]
