# Generated by Codex on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione_amministrativa", "0006_dipendente_materia"),
        ("gestione_finanziaria", "0004_conto_bancario_provider_account_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="bustapagadipendente",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoria finanziaria usata nei riepiloghi mensili delle spese.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buste_paga",
                to="gestione_finanziaria.categoriafinanziaria",
            ),
        ),
    ]
