# Generated by Django 5.2.13 on 2026-08-26 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0009_tipocontrattodipendente_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustapagadipendente',
            name='mese',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre'), (13, 'Tredicesima')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
