from django.urls import path

from sistema.permissions import module_edit_permission_required, module_permission_required

from . import views


gf_view = module_permission_required("gestione_finanziaria")
gf_manage = module_permission_required("gestione_finanziaria", level="manage")
gf_edit = module_edit_permission_required("gestione_finanziaria")


urlpatterns = [
    path(
        "gestione-finanziaria/",
        gf_view(views.dashboard_gestione_finanziaria),
        name="dashboard_gestione_finanziaria",
    ),

    # Fornitori e documenti passivi
    path(
        "gestione-finanziaria/categorie-spesa/",
        gf_view(views.lista_categorie_spesa),
        name="lista_categorie_spesa",
    ),
    path(
        "gestione-finanziaria/categorie-spesa/nuova/",
        gf_manage(views.crea_categoria_spesa),
        name="crea_categoria_spesa",
    ),
    path(
        "gestione-finanziaria/categorie-spesa/<int:pk>/modifica/",
        gf_edit(views.modifica_categoria_spesa),
        name="modifica_categoria_spesa",
    ),
    path(
        "gestione-finanziaria/categorie-spesa/<int:pk>/elimina/",
        gf_manage(views.elimina_categoria_spesa),
        name="elimina_categoria_spesa",
    ),
    path(
        "gestione-finanziaria/fornitori/",
        gf_view(views.lista_fornitori),
        name="lista_fornitori",
    ),
    path(
        "gestione-finanziaria/fornitori/nuovo/",
        gf_manage(views.crea_fornitore),
        name="crea_fornitore",
    ),
    path(
        "gestione-finanziaria/fornitori/<int:pk>/modifica/",
        gf_edit(views.modifica_fornitore),
        name="modifica_fornitore",
    ),
    path(
        "gestione-finanziaria/fornitori/<int:pk>/elimina/",
        gf_manage(views.elimina_fornitore),
        name="elimina_fornitore",
    ),
    path(
        "gestione-finanziaria/documenti-fornitori/",
        gf_view(views.lista_documenti_fornitori),
        name="lista_documenti_fornitori",
    ),
    path(
        "gestione-finanziaria/documenti-fornitori/nuovo/",
        gf_manage(views.crea_documento_fornitore),
        name="crea_documento_fornitore",
    ),
    path(
        "gestione-finanziaria/documenti-fornitori/elimina-selezionati/",
        gf_manage(views.elimina_documenti_fornitori_multipla),
        name="elimina_documenti_fornitori_multipla",
    ),
    path(
        "gestione-finanziaria/documenti-fornitori/<int:pk>/modifica/",
        gf_edit(views.modifica_documento_fornitore),
        name="modifica_documento_fornitore",
    ),
    path(
        "gestione-finanziaria/documenti-fornitori/<int:pk>/elimina/",
        gf_manage(views.elimina_documento_fornitore),
        name="elimina_documento_fornitore",
    ),
    path(
        "gestione-finanziaria/scadenziario-fornitori/",
        gf_view(views.scadenziario_fornitori),
        name="scadenziario_fornitori",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/",
        gf_view(views.lista_fatture_in_cloud),
        name="lista_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/nuova/",
        gf_manage(views.crea_fatture_in_cloud),
        name="crea_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/<int:pk>/modifica/",
        gf_manage(views.modifica_fatture_in_cloud),
        name="modifica_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/<int:pk>/elimina/",
        gf_manage(views.elimina_fatture_in_cloud),
        name="elimina_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/<int:pk>/oauth/",
        gf_manage(views.avvia_oauth_fatture_in_cloud),
        name="avvia_oauth_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/callback/",
        gf_manage(views.callback_fatture_in_cloud),
        name="callback_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/<int:pk>/sincronizza/",
        gf_manage(views.sincronizza_fatture_in_cloud_view),
        name="sincronizza_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/fatture-in-cloud/webhook/<uuid:webhook_key>/",
        views.webhook_fatture_in_cloud,
        name="webhook_fatture_in_cloud",
    ),
    path(
        "gestione-finanziaria/notifiche/",
        gf_view(views.lista_notifiche_finanziarie),
        name="lista_notifiche_finanziarie",
    ),
    path(
        "gestione-finanziaria/notifiche/<int:pk>/letta/",
        gf_view(views.segna_notifica_finanziaria_letta),
        name="segna_notifica_finanziaria_letta",
    ),
    path(
        "gestione-finanziaria/notifiche/segna-tutte-lette/",
        gf_view(views.segna_tutte_notifiche_finanziarie_lette),
        name="segna_tutte_notifiche_finanziarie_lette",
    ),
    path(
        "gestione-finanziaria/scadenze-fornitori/<int:pk>/pagamento/",
        gf_manage(views.registra_pagamento_scadenza_fornitore),
        name="registra_pagamento_scadenza_fornitore",
    ),
    path(
        "gestione-finanziaria/pagamenti-fornitori/<int:pk>/elimina/",
        gf_manage(views.elimina_pagamento_fornitore),
        name="elimina_pagamento_fornitore",
    ),

    # Provider bancari
    path(
        "gestione-finanziaria/provider/",
        gf_view(views.lista_provider_bancari),
        name="lista_provider_bancari",
    ),
    path(
        "gestione-finanziaria/provider/nuovo/",
        gf_manage(views.crea_provider_bancario),
        name="crea_provider_bancario",
    ),
    path(
        "gestione-finanziaria/provider/<int:pk>/modifica/",
        gf_edit(views.modifica_provider_bancario),
        name="modifica_provider_bancario",
    ),
    path(
        "gestione-finanziaria/provider/<int:pk>/elimina/",
        gf_manage(views.elimina_provider_bancario),
        name="elimina_provider_bancario",
    ),

    # Conti bancari
    path(
        "gestione-finanziaria/conti/",
        gf_view(views.lista_conti_bancari),
        name="lista_conti_bancari",
    ),
    path(
        "gestione-finanziaria/conti/nuovo/",
        gf_manage(views.crea_conto_bancario),
        name="crea_conto_bancario",
    ),
    path(
        "gestione-finanziaria/conti/<int:pk>/modifica/",
        gf_edit(views.modifica_conto_bancario),
        name="modifica_conto_bancario",
    ),
    path(
        "gestione-finanziaria/conti/<int:pk>/elimina/",
        gf_manage(views.elimina_conto_bancario),
        name="elimina_conto_bancario",
    ),
    path(
        "gestione-finanziaria/conti/<int:pk>/ricalcola-saldo/",
        gf_manage(views.ricalcola_saldo_conto_bancario),
        name="ricalcola_saldo_conto_bancario",
    ),
    path(
        "gestione-finanziaria/saldi-conti/",
        gf_view(views.lista_saldi_conti),
        name="lista_saldi_conti",
    ),
    path(
        "gestione-finanziaria/saldi-conti/nuovo/",
        gf_manage(views.crea_saldo_conto),
        name="crea_saldo_conto",
    ),
    path(
        "gestione-finanziaria/saldi-conti/import/",
        gf_manage(views.import_saldi_conti),
        name="import_saldi_conti",
    ),
    path(
        "gestione-finanziaria/saldi-conti/template-csv/",
        gf_view(views.scarica_template_saldi_conti_csv),
        name="scarica_template_saldi_conti_csv",
    ),
    path(
        "gestione-finanziaria/saldi-conti/<int:pk>/modifica/",
        gf_edit(views.modifica_saldo_conto),
        name="modifica_saldo_conto",
    ),
    path(
        "gestione-finanziaria/saldi-conti/<int:pk>/elimina/",
        gf_manage(views.elimina_saldo_conto),
        name="elimina_saldo_conto",
    ),

    # Movimenti finanziari
    path(
        "gestione-finanziaria/movimenti/",
        gf_view(views.lista_movimenti_finanziari),
        name="lista_movimenti_finanziari",
    ),
    path(
        "gestione-finanziaria/movimenti/nuovo/",
        gf_manage(views.crea_movimento_manuale),
        name="crea_movimento_manuale",
    ),
    path(
        "gestione-finanziaria/movimenti/ripulisci/",
        gf_manage(views.pulizia_movimenti_finanziari),
        name="pulizia_movimenti_finanziari",
    ),
    path(
        "gestione-finanziaria/movimenti/elimina-selezionati/",
        gf_manage(views.elimina_movimenti_finanziari_multipla),
        name="elimina_movimenti_finanziari_multipla",
    ),
    path(
        "gestione-finanziaria/movimenti/<int:pk>/modifica/",
        gf_edit(views.modifica_movimento_finanziario),
        name="modifica_movimento_finanziario",
    ),
    path(
        "gestione-finanziaria/movimenti/<int:pk>/elimina/",
        gf_manage(views.elimina_movimento_finanziario),
        name="elimina_movimento_finanziario",
    ),
    path(
        "gestione-finanziaria/movimenti/<int:pk>/annulla-riconciliazione/",
        gf_manage(views.annulla_riconciliazione_movimento),
        name="annulla_riconciliazione_movimento",
    ),

    # Regole di categorizzazione
    path(
        "gestione-finanziaria/regole/",
        gf_view(views.lista_regole_categorizzazione),
        name="lista_regole_categorizzazione",
    ),
    path(
        "gestione-finanziaria/regole/nuova/",
        gf_manage(views.crea_regola_categorizzazione),
        name="crea_regola_categorizzazione",
    ),
    path(
        "gestione-finanziaria/regole/<int:pk>/modifica/",
        gf_edit(views.modifica_regola_categorizzazione),
        name="modifica_regola_categorizzazione",
    ),
    path(
        "gestione-finanziaria/regole/<int:pk>/elimina/",
        gf_manage(views.elimina_regola_categorizzazione),
        name="elimina_regola_categorizzazione",
    ),
    path(
        "gestione-finanziaria/regole/applica-massiva/",
        gf_manage(views.applica_regole_massiva),
        name="applica_regole_massiva",
    ),

    # Import estratto conto (CAMT.053 / CSV)
    path(
        "gestione-finanziaria/import-estratto-conto/",
        gf_manage(views.import_estratto_conto),
        name="import_estratto_conto",
    ),

    # Connessioni PSD2
    path(
        "gestione-finanziaria/connessioni/",
        gf_view(views.lista_connessioni_bancarie),
        name="lista_connessioni_bancarie",
    ),
    path(
        "gestione-finanziaria/provider/<int:pk>/configura-psd2/",
        gf_manage(views.configura_provider_psd2),
        name="configura_provider_psd2",
    ),
    path(
        "gestione-finanziaria/provider/<int:provider_pk>/nuova-connessione/",
        gf_manage(views.nuova_connessione_psd2),
        name="nuova_connessione_psd2",
    ),
    path(
        "gestione-finanziaria/connessioni/<int:pk>/callback/",
        views.callback_connessione_psd2,
        name="callback_connessione_psd2",
    ),
    # Redirect URI *fisso* per provider OAuth2 (es. TrueLayer) che richiedono
    # una URL pre-registrata nella console dello sviluppatore. Il pk della
    # connessione viene estratto dal parametro "state" nell'URL di ritorno.
    path(
        "gestione-finanziaria/connessioni/oauth-callback/",
        views.callback_oauth_psd2,
        name="callback_oauth_psd2",
    ),
    path(
        "gestione-finanziaria/connessioni/<int:pk>/elimina/",
        gf_manage(views.elimina_connessione_psd2),
        name="elimina_connessione_psd2",
    ),
    path(
        "gestione-finanziaria/conti/<int:pk>/sincronizza/",
        gf_manage(views.sincronizza_conto_bancario),
        name="sincronizza_conto_bancario",
    ),

    # Pianificazione sincronizzazione PSD2
    path(
        "gestione-finanziaria/pianificazione-sincronizzazione/",
        gf_manage(views.pianificazione_sincronizzazione),
        name="pianificazione_sincronizzazione",
    ),

    # Riconciliazione movimenti <-> rate iscrizione
    path(
        "gestione-finanziaria/riconciliazione/",
        gf_view(views.lista_movimenti_da_riconciliare),
        name="lista_movimenti_da_riconciliare",
    ),
    path(
        "gestione-finanziaria/riconciliazione/<int:pk>/",
        gf_edit(views.riconcilia_movimento),
        name="riconcilia_movimento",
    ),
    path(
        "gestione-finanziaria/riconciliazione-fornitori/",
        gf_view(views.lista_movimenti_da_riconciliare_fornitori),
        name="lista_movimenti_da_riconciliare_fornitori",
    ),
    path(
        "gestione-finanziaria/riconciliazione-fornitori/<int:pk>/",
        gf_edit(views.riconcilia_movimento_fornitore),
        name="riconcilia_movimento_fornitore",
    ),

    # Report per categoria
    path(
        "gestione-finanziaria/report/categorie-mensile/",
        gf_view(views.report_categorie_mensile),
        name="report_categorie_mensile",
    ),
    path(
        "gestione-finanziaria/report/categorie-annuale/",
        gf_view(views.report_categorie_annuale),
        name="report_categorie_annuale",
    ),

    # Categorie finanziarie
    path(
        "gestione-finanziaria/categorie/",
        gf_view(views.lista_categorie_finanziarie),
        name="lista_categorie_finanziarie",
    ),
    path(
        "gestione-finanziaria/categorie/nuova/",
        gf_manage(views.crea_categoria_finanziaria),
        name="crea_categoria_finanziaria",
    ),
    path(
        "gestione-finanziaria/categorie/<int:pk>/modifica/",
        gf_edit(views.modifica_categoria_finanziaria),
        name="modifica_categoria_finanziaria",
    ),
    path(
        "gestione-finanziaria/categorie/<int:pk>/elimina/",
        gf_manage(views.elimina_categoria_finanziaria),
        name="elimina_categoria_finanziaria",
    ),
]
