# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('colore', models.CharField(default='#3b82f6', max_length=7)),
                ('chiave_sistema', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ordine', models.PositiveIntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria calendario',
                'verbose_name_plural': 'Categorie calendario',
                'db_table': 'claendario_categoria_calendario',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('tipologia', models.CharField(blank=True, max_length=120)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('intera_giornata', models.BooleanField(default=True)),
                ('ripetizione', models.CharField(choices=[('nessuna', 'Non si ripete'), ('giornaliera', 'Giornaliera'), ('giorni_feriali', 'Giorni feriali'), ('settimanale', 'Settimanale'), ('mensile', 'Mensile'), ('annuale', 'Annuale')], default='nessuna', max_length=20)),
                ('ripeti_ogni_intervallo', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('ripetizione_numero_occorrenze', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(260)])),
                ('ripetizione_fino_al', models.DateField(blank=True, null=True)),
                ('luogo', models.CharField(blank=True, max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('visibile', models.BooleanField(default=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_calendario_aggiornati', to=settings.AUTH_USER_MODEL)),
                ('categoria_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventi', to='calendario.categoriacalendario')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_calendario_creati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento calendario',
                'verbose_name_plural': 'Eventi calendario',
                'db_table': 'claendario_evento_calendario',
                'ordering': ['data_inizio', 'ora_inizio', 'titolo'],
            },
        ),
    ]
