# Generated by Django 5.2.13 on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scuola", "0003_extract_calendario_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="EventoCalendario",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("titolo", models.CharField(max_length=200)),
                        ("categoria", models.CharField(choices=[("didattico", "Didattici"), ("amministrativo", "Amministrativi")], max_length=20)),
                        ("tipologia", models.CharField(choices=[("colloqui", "Colloqui"), ("collegio_docenti", "Collegio Docenti / Riunioni di classe"), ("festa", "Feste"), ("evento", "Eventi"), ("altro_didattico", "Altri eventi didattici"), ("scadenza_documenti", "Scadenze documenti"), ("riunione_cda", "Riunioni CDA"), ("scadenza_rette", "Scadenze rette"), ("scadenza_fatture", "Scadenze fatture fornitori"), ("altro_amministrativo", "Altri eventi amministrativi")], max_length=40)),
                        ("data_inizio", models.DateField()),
                        ("data_fine", models.DateField()),
                        ("ora_inizio", models.TimeField(blank=True, null=True)),
                        ("ora_fine", models.TimeField(blank=True, null=True)),
                        ("intera_giornata", models.BooleanField(default=True)),
                        ("luogo", models.CharField(blank=True, max_length=200)),
                        ("descrizione", models.TextField(blank=True)),
                        ("visibile", models.BooleanField(default=True)),
                        ("attivo", models.BooleanField(default=True)),
                        ("data_creazione", models.DateTimeField(auto_now_add=True)),
                        ("data_aggiornamento", models.DateTimeField(auto_now=True)),
                        ("aggiornato_da", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="eventi_calendario_aggiornati", to=settings.AUTH_USER_MODEL)),
                        ("creato_da", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="eventi_calendario_creati", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "claendario_evento_calendario",
                        "verbose_name": "Evento calendario",
                        "verbose_name_plural": "Eventi calendario",
                        "ordering": ["data_inizio", "ora_inizio", "titolo"],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
