# Generated by Django 5.2.13 on 2026-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoGoogleCalendarioSincronizzato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, unique=True)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True)),
                ('luogo', models.CharField(blank=True, max_length=200)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('ora_inizio', models.TimeField(blank=True, null=True)),
                ('ora_fine', models.TimeField(blank=True, null=True)),
                ('intera_giornata', models.BooleanField(default=True)),
                ('html_link', models.URLField(blank=True)),
                ('stato_google', models.CharField(blank=True, max_length=50)),
                ('organizzatore_email', models.EmailField(blank=True, max_length=254)),
                ('attivo', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('data_aggiornamento_google', models.DateTimeField(blank=True, null=True)),
                ('data_sincronizzazione', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento Google sincronizzato',
                'verbose_name_plural': 'Eventi Google sincronizzati',
                'db_table': 'claendario_google_evento_sincronizzato',
                'ordering': ['data_inizio', 'ora_inizio', 'titolo'],
            },
        ),
    ]
