# Generated by Django 5.2.13 on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_calendar_categories(apps, schema_editor):
    CategoriaCalendario = apps.get_model("calendario", "CategoriaCalendario")
    EventoCalendario = apps.get_model("calendario", "EventoCalendario")

    didattici, _ = CategoriaCalendario.objects.get_or_create(
        nome="Didattici",
        defaults={"colore": "#3b82f6", "ordine": 1, "attiva": True},
    )
    amministrativi, _ = CategoriaCalendario.objects.get_or_create(
        nome="Amministrativi",
        defaults={"colore": "#22a06b", "ordine": 2, "attiva": True},
    )
    generale, _ = CategoriaCalendario.objects.get_or_create(
        nome="Generale",
        defaults={"colore": "#64748b", "ordine": 3, "attiva": True},
    )

    for evento in EventoCalendario.objects.all().iterator():
        if evento.categoria == "didattico":
            evento.categoria_evento_id = didattici.pk
        elif evento.categoria == "amministrativo":
            evento.categoria_evento_id = amministrativi.pk
        else:
            evento.categoria_evento_id = generale.pk
        evento.save(update_fields=["categoria_evento"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0002_eventogooglecalendariosincronizzato"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaCalendario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("colore", models.CharField(default="#3b82f6", max_length=7)),
                ("ordine", models.PositiveIntegerField(blank=True, null=True)),
                ("attiva", models.BooleanField(default=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_aggiornamento", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria calendario",
                "verbose_name_plural": "Categorie calendario",
                "db_table": "claendario_categoria_calendario",
                "ordering": ["ordine", "nome"],
            },
        ),
        migrations.AddField(
            model_name="eventocalendario",
            name="categoria_evento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventi",
                to="calendario.categoriacalendario",
            ),
        ),
        migrations.AlterField(
            model_name="eventocalendario",
            name="tipologia",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(migrate_existing_calendar_categories, noop_reverse),
        migrations.AlterField(
            model_name="eventocalendario",
            name="categoria_evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventi",
                to="calendario.categoriacalendario",
            ),
        ),
        migrations.RemoveField(
            model_name="eventocalendario",
            name="categoria",
        ),
        migrations.DeleteModel(
            name="EventoGoogleCalendarioSincronizzato",
        ),
    ]
