# Generated by Django 5.2.13 on 2026-05-11 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_categoria_visibile_dashboard'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriacalendario',
            table='calendario_categoria_calendario',
        ),
        migrations.AlterModelTable(
            name='eventocalendario',
            table='calendario_evento_calendario',
        ),
    ]
