# Generated by Django 5.2.13 on 2026-04-22 21:13

import django.core.validators
from django.db import migrations, models
from django.db.models import Max


SYSTEM_CATEGORY_DEFINITIONS = (
    {
        "key": "scadenze_rette",
        "name": "Scadenze rette",
        "color": "#be123c",
    },
    {
        "key": "documenti",
        "name": "Documenti",
        "color": "#b45309",
    },
)


def ensure_system_categories(apps, schema_editor):
    CategoriaCalendario = apps.get_model("calendario", "CategoriaCalendario")
    next_order = (CategoriaCalendario.objects.aggregate(max_ordine=Max("ordine"))["max_ordine"] or 0) + 1

    for definition in SYSTEM_CATEGORY_DEFINITIONS:
        categoria = CategoriaCalendario.objects.filter(chiave_sistema=definition["key"]).first()
        if not categoria:
            categoria = CategoriaCalendario.objects.filter(nome__iexact=definition["name"]).first()

        if categoria:
            update_fields = []
            if categoria.chiave_sistema != definition["key"]:
                categoria.chiave_sistema = definition["key"]
                update_fields.append("chiave_sistema")
            if not categoria.attiva:
                categoria.attiva = True
                update_fields.append("attiva")
            if not categoria.colore:
                categoria.colore = definition["color"]
                update_fields.append("colore")
            if not categoria.ordine:
                categoria.ordine = next_order
                next_order += 1
                update_fields.append("ordine")
            if update_fields:
                categoria.save(update_fields=update_fields)
            continue

        CategoriaCalendario.objects.create(
            nome=definition["name"],
            colore=definition["color"],
            chiave_sistema=definition["key"],
            ordine=next_order,
            attiva=True,
        )
        next_order += 1


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_categoria_calendario_and_cleanup_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacalendario',
            name='chiave_sistema',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='ripeti_ogni_settimane',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='ripetizione',
            field=models.CharField(choices=[('nessuna', 'Non si ripete'), ('settimanale', 'Settimanale')], default='nessuna', max_length=20),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='ripetizione_fino_al',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='ripetizione_numero_occorrenze',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(260)]),
        ),
        
    ]
