# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0001_initial'),
        ('scuola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServizioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servizio', models.CharField(max_length=150)),
                ('ordine', models.PositiveIntegerField(blank=True)),
                ('descrizione', models.TextField(blank=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servizi_extra', to='scuola.annoscolastico')),
            ],
            options={
                'verbose_name': 'Servizio extra',
                'verbose_name_plural': 'Servizi extra',
                'db_table': 'servizi_extra_servizio',
                'ordering': ['-anno_scolastico__data_inizio', 'ordine', 'nome_servizio'],
            },
        ),
        migrations.CreateModel(
            name='TariffaServizioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tariffa', models.CharField(max_length=150)),
                ('rateizzata', models.BooleanField(default=False)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffe', to='servizi_extra.servizioextra')),
            ],
            options={
                'verbose_name': 'Tariffa servizio extra',
                'verbose_name_plural': 'Tariffe servizi extra',
                'db_table': 'servizi_extra_tariffa',
                'ordering': ['servizio__anno_scolastico__data_inizio', 'servizio__nome_servizio', 'nome_tariffa'],
            },
        ),
        migrations.CreateModel(
            name='IscrizioneServizioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateField(blank=True, null=True)),
                ('data_fine_iscrizione', models.DateField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note_amministrative', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni_servizi_extra', to='anagrafica.studente')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iscrizioni', to='servizi_extra.servizioextra')),
                ('tariffa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iscrizioni', to='servizi_extra.tariffaservizioextra')),
            ],
            options={
                'verbose_name': 'Iscrizione servizio extra',
                'verbose_name_plural': 'Iscrizioni servizi extra',
                'db_table': 'servizi_extra_iscrizione',
                'ordering': ['-servizio__anno_scolastico__data_inizio', 'studente__cognome', 'studente__nome'],
            },
        ),
        migrations.CreateModel(
            name='TariffaServizioExtraRata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rata', models.PositiveIntegerField()),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('importo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_scadenza', models.DateField()),
                ('tariffa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_config', to='servizi_extra.tariffaservizioextra')),
            ],
            options={
                'verbose_name': 'Rata tariffa servizio extra',
                'verbose_name_plural': 'Rate tariffa servizi extra',
                'db_table': 'servizi_extra_tariffa_rata',
                'ordering': ['numero_rata', 'data_scadenza', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RataServizioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rata', models.PositiveIntegerField()),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('importo_dovuto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_scadenza', models.DateField()),
                ('pagata', models.BooleanField(default=False)),
                ('importo_pagato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=100)),
                ('importo_finale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('iscrizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='servizi_extra.iscrizioneservizioextra')),
            ],
            options={
                'verbose_name': 'Rata servizio extra',
                'verbose_name_plural': 'Rate servizi extra',
                'db_table': 'servizi_extra_rata',
                'ordering': ['data_scadenza', 'numero_rata', 'id'],
                'constraints': [models.UniqueConstraint(fields=('iscrizione', 'numero_rata'), name='unique_servizi_extra_rata_per_iscrizione')],
            },
        ),
        migrations.AddConstraint(
            model_name='servizioextra',
            constraint=models.UniqueConstraint(fields=('anno_scolastico', 'nome_servizio'), name='unique_servizi_extra_servizio_per_anno'),
        ),
        migrations.AddConstraint(
            model_name='tariffaservizioextra',
            constraint=models.UniqueConstraint(fields=('servizio', 'nome_tariffa'), name='unique_servizi_extra_tariffa_per_servizio'),
        ),
        migrations.AddConstraint(
            model_name='iscrizioneservizioextra',
            constraint=models.UniqueConstraint(fields=('studente', 'servizio'), name='unique_servizi_extra_iscrizione_studente_servizio'),
        ),
        migrations.AddConstraint(
            model_name='tariffaservizioextrarata',
            constraint=models.UniqueConstraint(fields=('tariffa', 'numero_rata'), name='unique_servizi_extra_tariffa_rata_numero'),
        ),
    ]
