# Generated by Django 5.2.13 on 2026-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servizi_extra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rataservizioextra',
            name='famiglia',
        ),
    ]
