# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0001_initial'),
        ('scuola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agevolazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_agevolazione', models.CharField(max_length=150, unique=True)),
                ('importo_annuale_agevolazione', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agevolazione',
                'verbose_name_plural': 'Agevolazioni',
                'db_table': 'economia_agevolazione',
                'ordering': ['nome_agevolazione'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pagamento', models.CharField(max_length=100, unique=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Metodo pagamento',
                'verbose_name_plural': 'Metodi pagamento',
                'db_table': 'economia_metodo_pagamento',
                'ordering': ['metodo_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='StatoIscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_iscrizione', models.CharField(max_length=100, unique=True)),
                ('ordine', models.PositiveIntegerField(blank=True)),
                ('attiva', models.BooleanField(db_column='attivo', default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stato iscrizione',
                'verbose_name_plural': 'Stati iscrizione',
                'db_table': 'economia_stato_iscrizione',
                'ordering': ['ordine', 'stato_iscrizione'],
            },
        ),
        migrations.CreateModel(
            name='TariffaScambioRetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_orario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('definizione', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tariffa scambio retta',
                'verbose_name_plural': 'Tariffe scambio retta',
                'db_table': 'economia_tariffa_scambio_retta',
                'ordering': ['valore_orario', 'definizione', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento_credito', models.CharField(max_length=100, unique=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo movimento credito',
                'verbose_name_plural': 'Tipi movimento credito',
                'db_table': 'economia_tipo_movimento_credito',
                'ordering': ['tipo_movimento_credito'],
            },
        ),
        migrations.CreateModel(
            name='CondizioneIscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_condizione_iscrizione', models.CharField(max_length=150)),
                ('numero_mensilita_default', models.PositiveIntegerField()),
                ('mese_prima_retta', models.PositiveSmallIntegerField(choices=[(1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre')], default=9, help_text="Mese di competenza da cui iniziare a generare le rette dell'anno scolastico.")),
                ('giorno_scadenza_rate', models.PositiveSmallIntegerField(blank=True, help_text='Giorno del mese usato per calcolare la scadenza di ciascuna rata.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('riduzione_speciale_ammessa', models.BooleanField(default=False)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condizioni_iscrizione', to='scuola.annoscolastico')),
            ],
            options={
                'verbose_name': 'Condizione iscrizione',
                'verbose_name_plural': 'Condizioni iscrizione',
                'db_table': 'economia_condizione_iscrizione',
                'ordering': ['-anno_scolastico__data_inizio', 'nome_condizione_iscrizione'],
            },
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateField(blank=True, null=True)),
                ('data_fine_iscrizione', models.DateField(blank=True, null=True)),
                ('riduzione_speciale', models.BooleanField(default=False)),
                ('importo_riduzione_speciale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('non_pagante', models.BooleanField(default=False)),
                ('modalita_pagamento_retta', models.CharField(choices=[('rateale', 'Rateale'), ('unica_soluzione', 'Unica soluzione')], default='rateale', max_length=20)),
                ('sconto_unica_soluzione_tipo', models.CharField(choices=[('nessuno', 'Nessuno'), ('percentuale', 'Percentuale'), ('importo', 'Importo fisso')], default='nessuno', max_length=20)),
                ('sconto_unica_soluzione_valore', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scadenza_pagamento_unica', models.DateField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note_amministrative', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('agevolazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iscrizioni', to='economia.agevolazione')),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iscrizioni', to='scuola.annoscolastico')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iscrizioni', to='scuola.classe')),
                ('condizione_iscrizione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iscrizioni', to='economia.condizioneiscrizione')),
                ('gruppo_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iscrizioni', to='scuola.gruppoclasse', verbose_name='Pluriclasse')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni', to='anagrafica.studente')),
                ('stato_iscrizione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iscrizioni', to='economia.statoiscrizione')),
            ],
            options={
                'verbose_name': 'Iscrizione',
                'verbose_name_plural': 'Iscrizioni',
                'db_table': 'economia_iscrizione',
                'ordering': ['-anno_scolastico__data_inizio', 'studente__cognome', 'studente__nome'],
            },
        ),
        migrations.CreateModel(
            name='RataIscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rata', models.CharField(choices=[('mensile', 'Mensile'), ('preiscrizione', 'Preiscrizione'), ('unica_soluzione', 'Unica soluzione')], default='mensile', max_length=20)),
                ('numero_rata', models.PositiveIntegerField()),
                ('mese_riferimento', models.PositiveIntegerField()),
                ('anno_riferimento', models.PositiveIntegerField()),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('importo_dovuto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('pagata', models.BooleanField(default=False)),
                ('importo_pagato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('credito_applicato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('altri_sgravi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importo_finale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('iscrizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='economia.iscrizione')),
                ('metodo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_iscrizione', to='economia.metodopagamento')),
            ],
            options={
                'verbose_name': 'Rata iscrizione',
                'verbose_name_plural': 'Rate iscrizione',
                'db_table': 'economia_rata_iscrizione',
                'ordering': ['anno_riferimento', 'mese_riferimento', 'numero_rata'],
            },
        ),
        migrations.CreateModel(
            name='ScambioRetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese_riferimento', models.PositiveSmallIntegerField()),
                ('descrizione', models.TextField(blank=True)),
                ('ore_lavorate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('importo_maturato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approvata', models.BooleanField(default=False)),
                ('contabilizzata', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scambi_retta', to='scuola.annoscolastico')),
                ('familiare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scambi_retta', to='anagrafica.familiare')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scambi_retta', to='anagrafica.studente')),
                ('tariffa_scambio_retta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scambi_retta', to='economia.tariffascambioretta')),
            ],
            options={
                'verbose_name': 'Scambio retta',
                'verbose_name_plural': 'Scambi retta',
                'db_table': 'economia_scambio_retta',
                'ordering': ['-anno_scolastico__data_inizio', '-mese_riferimento', 'studente__cognome', 'studente__nome'],
            },
        ),
        migrations.CreateModel(
            name='TariffaCondizioneIscrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine_figlio_da', models.PositiveIntegerField(blank=True)),
                ('ordine_figlio_a', models.PositiveIntegerField(blank=True, null=True)),
                ('retta_annuale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preiscrizione', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('condizione_iscrizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffe', to='economia.condizioneiscrizione')),
            ],
            options={
                'verbose_name': 'Tariffa condizione iscrizione',
                'verbose_name_plural': 'Tariffe condizione iscrizione',
                'db_table': 'economia_tariffa_condizione_iscrizione',
                'ordering': ['condizione_iscrizione', 'ordine_figlio_da', 'ordine_figlio_a', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrestazioneScambioRetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_ingresso', models.TimeField(blank=True, null=True)),
                ('ora_uscita', models.TimeField(blank=True, null=True)),
                ('descrizione', models.CharField(max_length=255, verbose_name='Mansione svolta')),
                ('ore_lavorate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('importo_maturato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='scuola.annoscolastico')),
                ('familiare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='anagrafica.familiare')),
                ('studente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='anagrafica.studente')),
                ('tariffa_scambio_retta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='economia.tariffascambioretta')),
            ],
            options={
                'verbose_name': 'Prestazione scambio retta',
                'verbose_name_plural': 'Prestazioni scambio retta',
                'db_table': 'economia_prestazione_scambio_retta',
                'ordering': ['-data', '-ora_ingresso', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCreditoRetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_progressivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descrizione', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('iscrizione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_credito_retta', to='economia.iscrizione')),
                ('studente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_credito_retta', to='anagrafica.studente')),
                ('rata_iscrizione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_credito_retta', to='economia.rataiscrizione')),
                ('scambio_retta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_credito_retta', to='economia.scambioretta')),
                ('tipo_movimento_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti_credito_retta', to='economia.tipomovimentocredito')),
            ],
            options={
                'verbose_name': 'Movimento credito retta',
                'verbose_name_plural': 'Movimenti credito retta',
                'db_table': 'economia_movimento_credito_retta',
                'ordering': ['data_movimento', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='condizioneiscrizione',
            constraint=models.UniqueConstraint(fields=('anno_scolastico', 'nome_condizione_iscrizione'), name='unique_economia_condizione_iscrizione_per_anno'),
        ),
        migrations.AddConstraint(
            model_name='iscrizione',
            constraint=models.UniqueConstraint(fields=('studente', 'anno_scolastico'), name='unique_economia_iscrizione_studente_anno'),
        ),
    ]
