# Generated by Codex on 2026-05-12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("economia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iscrizione",
            name="rate_custom",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Numero di rate concordato per questa iscrizione. Lascia vuoto per usare la condizione economica.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(36),
                ],
            ),
        ),
        migrations.CreateModel(
            name="RimodulazioneRetta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_decorrenza", models.DateField()),
                (
                    "modalita",
                    models.CharField(
                        choices=[
                            ("ridistribuisci_residuo", "Ridistribuisci il residuo attuale"),
                            ("importo_mensile", "Imposta un nuovo importo mensile"),
                            ("totale_residuo", "Ripartisci un nuovo totale residuo"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "numero_rate_future",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(36),
                        ],
                    ),
                ),
                ("importo_mensile", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("totale_precedente", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("totale_rimodulato", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("rate_sostituite", models.PositiveSmallIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("creata_il", models.DateTimeField(auto_now_add=True)),
                (
                    "creata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rimodulazioni_retta_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iscrizione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rimodulazioni_retta",
                        to="economia.iscrizione",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rimodulazione retta",
                "verbose_name_plural": "Rimodulazioni retta",
                "db_table": "economia_rimodulazione_retta",
                "ordering": ["-data_decorrenza", "-id"],
            },
        ),
    ]
