# Generated by Django 5.2.13 on 2026-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0003_realign_economia_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condizioneiscrizione',
            options={'ordering': ['-anno_scolastico__data_inizio', 'nome_condizione_iscrizione'], 'verbose_name': 'Condizione iscrizione', 'verbose_name_plural': 'Condizioni iscrizione'},
        ),
        migrations.AlterModelOptions(
            name='statoiscrizione',
            options={'ordering': ['ordine', 'stato_iscrizione'], 'verbose_name': 'Stato iscrizione', 'verbose_name_plural': 'Stati iscrizione'},
        ),
        migrations.AlterModelOptions(
            name='tariffacondizioneiscrizione',
            options={'ordering': ['condizione_iscrizione', 'ordine_figlio', 'id'], 'verbose_name': 'Tariffa condizione iscrizione', 'verbose_name_plural': 'Tariffe condizione iscrizione'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='statoiscrizione',
                    old_name='attivo',
                    new_name='attiva',
                ),
                migrations.AlterField(
                    model_name='statoiscrizione',
                    name='attiva',
                    field=models.BooleanField(db_column='attivo', default=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='tariffacondizioneiscrizione',
            name='ordine_figlio',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tariffacondizioneiscrizione',
            name='retta_annuale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
