# Generated by Django 5.2.13 on 2026-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0008_tariffa_condizione_fasce_figli'),
    ]

    operations = [
        migrations.AddField(
            model_name='condizioneiscrizione',
            name='mese_prima_retta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre')], default=9, help_text="Mese di competenza da cui iniziare a generare le rette dell'anno scolastico."),
        ),
    ]
