# Generated by Django 5.2.13 on 2026-04-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economia", "0009_condizioneiscrizione_mese_prima_retta"),
    ]

    operations = [
        migrations.AddField(
            model_name="rataiscrizione",
            name="tipo_rata",
            field=models.CharField(
                choices=[("mensile", "Mensile"), ("preiscrizione", "Preiscrizione")],
                default="mensile",
                max_length=20,
            ),
        ),
    ]
