# Generated by Django 5.2.13 on 2026-04-23 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0008_citta_codice_catastale_familiare_sesso_and_more'),
        ('economia', '0010_rataiscrizione_tipo_rata'),
        ('scuola', '0003_extract_calendario_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestazioneScambioRetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_ingresso', models.TimeField(blank=True, null=True)),
                ('ora_uscita', models.TimeField(blank=True, null=True)),
                ('descrizione', models.CharField(max_length=255, verbose_name='Mansione svolta')),
                ('ore_lavorate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('importo_maturato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='scuola.annoscolastico')),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='anagrafica.famiglia')),
                ('familiare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='anagrafica.familiare')),
                ('studente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='anagrafica.studente')),
                ('tariffa_scambio_retta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='economia.tariffascambioretta')),
            ],
            options={
                'verbose_name': 'Prestazione scambio retta',
                'verbose_name_plural': 'Prestazioni scambio retta',
                'db_table': 'economia_prestazione_scambio_retta',
                'ordering': ['-data', '-ora_ingresso', '-id'],
            },
        ),
    ]
