# Generated by Django 5.2.13 on 2026-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0011_prestazionescambioretta'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='modalita_pagamento_retta',
            field=models.CharField(choices=[('rateale', 'Rateale'), ('unica_soluzione', 'Unica soluzione')], default='rateale', max_length=20),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='scadenza_pagamento_unica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='sconto_unica_soluzione_tipo',
            field=models.CharField(choices=[('nessuno', 'Nessuno'), ('percentuale', 'Percentuale'), ('importo', 'Importo fisso')], default='nessuno', max_length=20),
        ),
        migrations.AddField(
            model_name='iscrizione',
            name='sconto_unica_soluzione_valore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rataiscrizione',
            name='tipo_rata',
            field=models.CharField(choices=[('mensile', 'Mensile'), ('preiscrizione', 'Preiscrizione'), ('unica_soluzione', 'Unica soluzione')], default='mensile', max_length=20),
        ),
    ]
