# Generated by Django 5.2.13 on 2026-04-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0012_iscrizione_modalita_pagamento_retta_and_more'),
        ('scuola', '0005_gruppoclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizione',
            name='gruppo_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iscrizioni', to='scuola.gruppoclasse'),
        ),
    ]
