# Generated by Django 5.2.13 on 2026-04-29 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0013_iscrizione_gruppo_classe'),
        ('scuola', '0006_alter_classe_options_alter_gruppoclasse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscrizione',
            name='gruppo_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iscrizioni', to='scuola.gruppoclasse', verbose_name='Pluriclasse'),
        ),
    ]
