# Generated by Django 5.2.13 on 2026-05-09 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0014_alter_familiare_famiglia_alter_studente_famiglia'),
        ('economia', '0014_alter_iscrizione_gruppo_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestazionescambioretta',
            name='famiglia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestazioni_scambio_retta', to='anagrafica.famiglia'),
        ),
        migrations.AlterField(
            model_name='scambioretta',
            name='famiglia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scambi_retta', to='anagrafica.famiglia'),
        ),
    ]
