# Generated by Django 5.2.13 on 2026-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0015_alter_prestazionescambioretta_famiglia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scambioretta',
            options={'ordering': ['-anno_scolastico__data_inizio', '-mese_riferimento', 'studente__cognome', 'studente__nome'], 'verbose_name': 'Scambio retta', 'verbose_name_plural': 'Scambi retta'},
        ),
        migrations.RemoveField(
            model_name='movimentocreditoretta',
            name='famiglia',
        ),
        migrations.RemoveField(
            model_name='prestazionescambioretta',
            name='famiglia',
        ),
        migrations.RemoveField(
            model_name='rataiscrizione',
            name='famiglia',
        ),
        migrations.RemoveField(
            model_name='scambioretta',
            name='famiglia',
        ),
    ]
