# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scuola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivioAnnoScolastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_anno_scolastico', models.CharField(max_length=50)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('data_archiviazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('totale_snapshot', models.PositiveIntegerField(default=0)),
                ('totale_studenti', models.PositiveIntegerField(default=0)),
                ('totale_famiglie', models.PositiveIntegerField(default=0)),
                ('totale_iscrizioni', models.PositiveIntegerField(default=0)),
                ('totale_rate', models.PositiveIntegerField(default=0)),
                ('totale_osservazioni', models.PositiveIntegerField(default=0)),
                ('totale_documenti', models.PositiveIntegerField(default=0)),
                ('anno_scolastico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='archivio_storico', to='scuola.annoscolastico')),
                ('archiviato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anni_scolastici_archiviati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivio anno scolastico',
                'verbose_name_plural': 'Archivio anni scolastici',
                'db_table': 'archivio_storico_anno_scolastico',
                'ordering': ['-data_inizio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('classe', 'Classe'), ('famiglia', 'Famiglia'), ('familiare', 'Familiare'), ('studente', 'Studente'), ('iscrizione', 'Iscrizione'), ('rata', 'Rata'), ('osservazione', 'Osservazione'), ('documento', 'Documento')], max_length=30)),
                ('source_app_label', models.CharField(max_length=80)),
                ('source_model', models.CharField(max_length=80)),
                ('source_pk', models.CharField(max_length=80)),
                ('titolo', models.CharField(max_length=255)),
                ('dati', models.JSONField(default=dict)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('archivio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='archivio_storico.archivioannoscolastico')),
            ],
            options={
                'verbose_name': 'Snapshot storico',
                'verbose_name_plural': 'Snapshot storici',
                'db_table': 'archivio_storico_snapshot',
                'ordering': ['tipo', 'ordine', 'titolo', 'id'],
                'indexes': [models.Index(fields=['archivio', 'tipo'], name='arch_stor_snap_arch_tipo_idx'), models.Index(fields=['source_app_label', 'source_model', 'source_pk'], name='arch_stor_snap_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('archivio', 'tipo', 'source_app_label', 'source_model', 'source_pk'), name='unique_archivio_snapshot_source')],
            },
        ),
    ]
