# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scuola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamigliaInteressata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome libero della famiglia o riferimento usato durante il primo contatto.', max_length=200)),
                ('referente_principale', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fonte_contatto', models.CharField(choices=[('sito', 'Sito web'), ('telefono', 'Telefono'), ('email', 'Email'), ('open_day', 'Open day'), ('passaparola', 'Passaparola'), ('social', 'Social'), ('altro', 'Altro')], default='altro', max_length=30)),
                ('fonte_note', models.CharField(blank=True, max_length=255)),
                ('stato', models.CharField(choices=[('nuovo_contatto', 'Nuovo contatto'), ('da_ricontattare', 'Da ricontattare'), ('colloquio_fissato', 'Colloquio fissato'), ('colloquio_svolto', 'Colloquio svolto'), ('in_valutazione', 'In valutazione'), ('lista_attesa', 'Lista attesa'), ('iscrizione_avviata', 'Iscrizione avviata'), ('convertita', 'Convertita'), ('non_interessata', 'Non interessata'), ('archiviata', 'Archiviata')], db_index=True, default='nuovo_contatto', max_length=30)),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('normale', 'Normale'), ('alta', 'Alta')], db_index=True, default='normale', max_length=20)),
                ('classe_eta_interesse', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('privacy_consenso', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('aggiornata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='famiglie_interessate_aggiornate', to=settings.AUTH_USER_MODEL)),
                ('anno_scolastico_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='famiglie_interessate', to='scuola.annoscolastico')),
                ('creata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='famiglie_interessate_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Famiglia interessata',
                'verbose_name_plural': 'Famiglie interessate',
                'db_table': 'famiglie_interessate_famiglia',
                'ordering': ['-data_aggiornamento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttivitaFamigliaInteressata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefonata', 'Telefonata'), ('email', 'Email'), ('messaggio', 'Messaggio'), ('colloquio', 'Colloquio'), ('visita', 'Visita'), ('open_day', 'Open day'), ('follow_up', 'Follow-up'), ('nota', 'Nota'), ('altro', 'Altro')], db_index=True, default='follow_up', max_length=30)),
                ('titolo', models.CharField(blank=True, max_length=200)),
                ('stato', models.CharField(choices=[('programmata', 'Programmata'), ('completata', 'Completata'), ('annullata', 'Annullata')], db_index=True, default='programmata', max_length=20)),
                ('data_programmata', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('durata_minuti', models.PositiveSmallIntegerField(default=30)),
                ('data_svolgimento', models.DateTimeField(blank=True, null=True)),
                ('calendarizza', models.BooleanField(default=True)),
                ('luogo', models.CharField(blank=True, max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('esito', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('assegnata_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attivita_famiglie_interessate_assegnate', to=settings.AUTH_USER_MODEL)),
                ('creata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attivita_famiglie_interessate_create', to=settings.AUTH_USER_MODEL)),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attivita', to='famiglie_interessate.famigliainteressata')),
            ],
            options={
                'verbose_name': 'Attivita famiglia interessata',
                'verbose_name_plural': 'Attivita famiglie interessate',
                'db_table': 'famiglie_interessate_attivita',
                'ordering': ['-data_programmata', '-data_creazione', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MinoreInteressato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('eta_indicativa', models.CharField(blank=True, max_length=80)),
                ('classe_eta_interesse', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('classe_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minori_interessati', to='scuola.classe')),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minori', to='famiglie_interessate.famigliainteressata')),
            ],
            options={
                'verbose_name': 'Minore interessato',
                'verbose_name_plural': 'Minori interessati',
                'db_table': 'famiglie_interessate_minore',
                'ordering': ['data_nascita', 'cognome', 'nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenteFamigliaInteressata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('relazione', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('principale', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenti', to='famiglie_interessate.famigliainteressata')),
            ],
            options={
                'verbose_name': 'Referente famiglia interessata',
                'verbose_name_plural': 'Referenti famiglie interessate',
                'db_table': 'famiglie_interessate_referente',
                'ordering': ['-principale', 'nome', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='famigliainteressata',
            index=models.Index(fields=['stato', 'priorita'], name='fam_int_stato_priorita_idx'),
        ),
        migrations.AddIndex(
            model_name='famigliainteressata',
            index=models.Index(fields=['fonte_contatto', 'data_creazione'], name='fam_int_fonte_data_idx'),
        ),
        migrations.AddIndex(
            model_name='attivitafamigliainteressata',
            index=models.Index(fields=['stato', 'data_programmata'], name='fam_int_att_stato_data_idx'),
        ),
        migrations.AddIndex(
            model_name='attivitafamigliainteressata',
            index=models.Index(fields=['tipo', 'data_programmata'], name='fam_int_att_tipo_data_idx'),
        ),
    ]
