# Generated by Django 5.2.13 on 2026-05-03 21:12

import django.db.models.deletion
from django.db import migrations, models


def collega_classi_da_testo(apps, schema_editor):
    Classe = apps.get_model('scuola', 'Classe')
    MinoreInteressato = apps.get_model('famiglie_interessate', 'MinoreInteressato')

    classi_lookup = {}
    for classe in Classe.objects.all():
        nome = (classe.nome_classe or '').strip()
        sezione = (classe.sezione_classe or '').strip()
        labels = {nome, f'{nome} {sezione}'.strip()}
        for label in labels:
            if label:
                classi_lookup.setdefault(label.casefold(), classe.pk)

    for minore in MinoreInteressato.objects.filter(classe_interesse__isnull=True).exclude(classe_eta_interesse=''):
        classe_id = classi_lookup.get((minore.classe_eta_interesse or '').strip().casefold())
        if classe_id:
            minore.classe_interesse_id = classe_id
            minore.save(update_fields=['classe_interesse'])


class Migration(migrations.Migration):

    dependencies = [
        ('famiglie_interessate', '0001_initial'),
        ('scuola', '0006_alter_classe_options_alter_gruppoclasse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minoreinteressato',
            name='classe_interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minori_interessati', to='scuola.classe'),
        ),
        migrations.RunPython(collega_classi_da_testo, migrations.RunPython.noop),
    ]
