# Generated by Django 5.2.13 on 2026-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famiglie_interessate', '0002_minoreinteressato_classe_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famigliainteressata',
            name='convertita_in_famiglia',
        ),
    ]
