# Generated by Django 5.2.13 on 2026-05-10 11:18

import anagrafica.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codice_istat', models.CharField(blank=True, db_index=True, max_length=10)),
                ('codice_catastale', models.CharField(blank=True, db_index=True, max_length=4)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Città',
                'verbose_name_plural': 'Città',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LabelEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etichetta email',
                'verbose_name_plural': 'Etichette email',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LabelIndirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etichetta indirizzo',
                'verbose_name_plural': 'Etichette indirizzi',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LabelTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etichetta telefono',
                'verbose_name_plural': 'Etichette telefoni',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'ordering': ['ordine', 'sigla'],
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RelazioneFamiliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relazione', models.CharField(max_length=100, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Relazione familiare',
                'verbose_name_plural': 'Relazioni familiari',
                'ordering': ['ordine', 'relazione'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipi documento',
                'ordering': ['ordine', 'tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='CAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('citta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_list', to='anagrafica.citta')),
            ],
            options={
                'verbose_name': 'CAP',
                'verbose_name_plural': 'CAP',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=200)),
                ('numero_civico', models.CharField(blank=True, max_length=20)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('cap_scelto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.cap')),
                ('citta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.citta')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.provincia')),
                ('regione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.regione')),
            ],
            options={
                'verbose_name': 'Indirizzo',
                'verbose_name_plural': 'Indirizzi',
            },
        ),
        migrations.CreateModel(
            name='AnagraficaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('principale', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti', to='anagrafica.labelemail')),
            ],
            options={
                'verbose_name': 'Email anagrafica',
                'verbose_name_plural': 'Email anagrafiche',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnagraficaIndirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('principale', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('indirizzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collegamenti_anagrafici', to='anagrafica.indirizzo')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti', to='anagrafica.labelindirizzo')),
            ],
            options={
                'verbose_name': 'Indirizzo anagrafico',
                'verbose_name_plural': 'Indirizzi anagrafici',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnagraficaTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('numero', models.CharField(max_length=40)),
                ('principale', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti', to='anagrafica.labeltelefono')),
            ],
            options={
                'verbose_name': 'Telefono anagrafico',
                'verbose_name_plural': 'Telefoni anagrafici',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Nazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('nome_nazionalita', models.CharField(blank=True, max_length=120)),
                ('codice_iso2', models.CharField(blank=True, max_length=2)),
                ('codice_iso3', models.CharField(blank=True, max_length=3)),
                ('codice_belfiore', models.CharField(blank=True, db_index=True, max_length=4)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nazione',
                'verbose_name_plural': 'Nazioni',
                'ordering': ['ordine', 'nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codice_belfiore', ''), _negated=True), fields=('codice_belfiore',), name='unique_nazione_codice_belfiore_non_vuoto')],
            },
        ),
        migrations.AddField(
            model_name='citta',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citta', to='anagrafica.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='regione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province', to='anagrafica.regione'),
        ),
        migrations.CreateModel(
            name='Familiare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('luogo_nascita_custom', models.CharField(blank=True, max_length=160)),
                ('convivente', models.BooleanField(default=False)),
                ('referente_principale', models.BooleanField(default=False)),
                ('abilitato_scambio_retta', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('luogo_nascita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familiari_nati', to='anagrafica.citta')),
                ('indirizzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiari', to='anagrafica.indirizzo')),
                ('nazionalita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familiari_nazionalita', to='anagrafica.nazione')),
                ('nazione_nascita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familiari_nati', to='anagrafica.nazione')),
                ('relazione_familiare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familiari', to='anagrafica.relazionefamiliare')),
            ],
            options={
                'verbose_name': 'Familiare',
                'verbose_name_plural': 'Familiari',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('luogo_nascita_custom', models.CharField(blank=True, max_length=160)),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('indirizzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studenti', to='anagrafica.indirizzo')),
                ('luogo_nascita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studenti_nati', to='anagrafica.citta')),
                ('nazionalita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studenti_nazionalita', to='anagrafica.nazione')),
                ('nazione_nascita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studenti_nati', to='anagrafica.nazione')),
            ],
            options={
                'verbose_name': 'Studente',
                'verbose_name_plural': 'Studenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='StudenteFamiliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referente_principale', models.BooleanField(default=False)),
                ('convivente', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('familiare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazioni_studenti', to='anagrafica.familiare')),
                ('relazione_familiare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relazioni_studenti', to='anagrafica.relazionefamiliare')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazioni_familiari', to='anagrafica.studente')),
            ],
            options={
                'verbose_name': 'Relazione studente-familiare',
                'verbose_name_plural': 'Relazioni studenti-familiari',
                'ordering': ['studente__cognome', 'studente__nome', 'familiare__cognome', 'familiare__nome'],
            },
        ),
        migrations.AddField(
            model_name='studente',
            name='familiari',
            field=models.ManyToManyField(blank=True, related_name='studenti_collegati', through='anagrafica.StudenteFamiliare', to='anagrafica.familiare'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True)),
                ('file', models.FileField(max_length=255, upload_to=anagrafica.models.documento_upload_to)),
                ('data_caricamento', models.DateField(auto_now_add=True)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('visibile', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('familiare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.familiare')),
                ('studente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.studente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='anagrafica.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['-data_caricamento', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cap',
            constraint=models.UniqueConstraint(fields=('codice', 'citta'), name='unique_cap_citta'),
        ),
        migrations.AddIndex(
            model_name='anagraficaemail',
            index=models.Index(fields=['content_type', 'object_id'], name='anag_email_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='anagraficaemail',
            index=models.Index(fields=['email'], name='anag_email_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='anagraficaemail',
            constraint=models.UniqueConstraint(condition=models.Q(('principale', True)), fields=('content_type', 'object_id'), name='unique_email_principale'),
        ),
        migrations.AddIndex(
            model_name='anagraficaindirizzo',
            index=models.Index(fields=['content_type', 'object_id'], name='anag_ind_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='anagraficaindirizzo',
            constraint=models.UniqueConstraint(condition=models.Q(('principale', True)), fields=('content_type', 'object_id'), name='unique_indirizzo_principale'),
        ),
        migrations.AddIndex(
            model_name='anagraficatelefono',
            index=models.Index(fields=['content_type', 'object_id'], name='anag_tel_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='anagraficatelefono',
            index=models.Index(fields=['numero'], name='anag_tel_numero_idx'),
        ),
        migrations.AddConstraint(
            model_name='anagraficatelefono',
            constraint=models.UniqueConstraint(condition=models.Q(('principale', True)), fields=('content_type', 'object_id'), name='unique_telefono_principale'),
        ),
        migrations.AddConstraint(
            model_name='citta',
            constraint=models.UniqueConstraint(fields=('nome', 'provincia'), name='unique_citta_provincia'),
        ),
        migrations.AddConstraint(
            model_name='studentefamiliare',
            constraint=models.UniqueConstraint(fields=('studente', 'familiare'), name='unique_studente_familiare'),
        ),
    ]
