# Generated by Django 5.2.13 on 2026-04-15 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('ordine', models.IntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Città',
                'verbose_name_plural': 'Città',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.IntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'ordering': ['ordine', 'sigla'],
            },
        ),
        migrations.CreateModel(
            name='RelazioneFamiliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relazione', models.CharField(max_length=100, unique=True)),
                ('ordine', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Relazione familiare',
                'verbose_name_plural': 'Relazioni familiari',
                'ordering': ['ordine', 'relazione'],
            },
        ),
        migrations.CreateModel(
            name='StatoRelazioneFamiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(max_length=100, unique=True)),
                ('ordine', models.IntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stato relazione famiglia',
                'verbose_name_plural': 'Stati relazione famiglia',
                'ordering': ['ordine', 'stato'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100, unique=True)),
                ('ordine', models.IntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipi documento',
                'ordering': ['ordine', 'tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(max_length=200)),
                ('numero_civico', models.CharField(blank=True, max_length=20)),
                ('cap', models.CharField(blank=True, max_length=10)),
                ('nazione', models.CharField(default='Italia', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('citta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.citta')),
            ],
            options={
                'verbose_name': 'Indirizzo',
                'verbose_name_plural': 'Indirizzi',
                'ordering': ['citta__nome', 'indirizzo', 'numero_civico'],
            },
        ),
        migrations.CreateModel(
            name='Famiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome_famiglia', models.CharField(max_length=150)),
                ('attiva', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('indirizzo_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='famiglie_principali', to='anagrafica.indirizzo')),
                ('stato_relazione_famiglia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='famiglie', to='anagrafica.statorelazionefamiglia')),
            ],
            options={
                'verbose_name': 'Famiglia',
                'verbose_name_plural': 'Famiglie',
                'ordering': ['cognome_famiglia'],
            },
        ),
        migrations.AddField(
            model_name='citta',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citta', to='anagrafica.provincia'),
        ),
        migrations.CreateModel(
            name='Familiare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('luogo_nascita', models.CharField(blank=True, max_length=100)),
                ('convivente', models.BooleanField(default=False)),
                ('referente_principale', models.BooleanField(default=False)),
                ('abilitato_scambio_retta', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiari', to='anagrafica.famiglia')),
                ('indirizzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiari', to='anagrafica.indirizzo')),
                ('relazione_familiare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familiari', to='anagrafica.relazionefamiliare')),
            ],
            options={
                'verbose_name': 'Familiare',
                'verbose_name_plural': 'Familiari',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('luogo_nascita', models.CharField(blank=True, max_length=100)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studenti', to='anagrafica.famiglia')),
                ('indirizzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studenti', to='anagrafica.indirizzo')),
            ],
            options={
                'verbose_name': 'Studente',
                'verbose_name_plural': 'Studenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documenti/')),
                ('data_caricamento', models.DateField(auto_now_add=True)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('visibile', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('famiglia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.famiglia')),
                ('familiare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.familiare')),
                ('studente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.studente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='anagrafica.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['-data_caricamento', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='indirizzo',
            constraint=models.UniqueConstraint(fields=('indirizzo', 'numero_civico', 'cap', 'citta', 'nazione'), name='unique_indirizzo_completo'),
        ),
        migrations.AddConstraint(
            model_name='citta',
            constraint=models.UniqueConstraint(fields=('nome', 'provincia'), name='unique_citta_provincia'),
        ),
    ]
