# Generated by Django 5.2.13 on 2026-04-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ordine', models.IntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='regione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province', to='anagrafica.regione'),
        ),
    ]
