# Generated by Django 5.2.13 on 2026-04-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_regione_provincia_regione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indirizzo',
            options={'verbose_name': 'Indirizzo', 'verbose_name_plural': 'Indirizzi'},
        ),
        migrations.RemoveConstraint(
            model_name='indirizzo',
            name='unique_indirizzo_completo',
        ),
        migrations.RenameField(
            model_name='indirizzo',
            old_name='indirizzo',
            new_name='via',
        ),
        migrations.RemoveField(
            model_name='indirizzo',
            name='nazione',
        ),
        migrations.RemoveField(
            model_name='indirizzo',
            name='note',
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.provincia'),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='regione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.regione'),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='citta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.citta'),
        ),
    ]
