# Generated by Django 5.2.13 on 2026-05-11 00:33

import django.db.models.deletion
from django.db import migrations, models


def seed_persone_da_familiari(apps, schema_editor):
    Familiare = apps.get_model("anagrafica", "Familiare")
    Persona = apps.get_model("anagrafica", "Persona")
    db_alias = schema_editor.connection.alias

    for familiare in Familiare.objects.using(db_alias).all().iterator():
        if familiare.persona_id:
            continue
        codice_fiscale = (familiare.codice_fiscale or "").upper().strip()
        if codice_fiscale and Persona.objects.using(db_alias).filter(codice_fiscale=codice_fiscale).exists():
            codice_fiscale = ""
        persona = Persona.objects.using(db_alias).create(
            indirizzo_id=familiare.indirizzo_id,
            nome=familiare.nome or "",
            cognome=familiare.cognome or "",
            sesso=familiare.sesso or "",
            data_nascita=familiare.data_nascita,
            luogo_nascita_id=familiare.luogo_nascita_id,
            nazione_nascita_id=familiare.nazione_nascita_id,
            luogo_nascita_custom=familiare.luogo_nascita_custom or "",
            nazionalita_id=familiare.nazionalita_id,
            codice_fiscale=codice_fiscale,
            email=familiare.email or "",
            telefono=familiare.telefono or "",
            note=familiare.note or "",
        )
        Familiare.objects.using(db_alias).filter(pk=familiare.pk).update(persona_id=persona.pk)


def unseed_persone_da_familiari(apps, schema_editor):
    Familiare = apps.get_model("anagrafica", "Familiare")
    Persona = apps.get_model("anagrafica", "Persona")
    db_alias = schema_editor.connection.alias
    persona_ids = list(
        Familiare.objects.using(db_alias)
        .exclude(persona_id__isnull=True)
        .values_list("persona_id", flat=True)
    )
    Familiare.objects.using(db_alias).update(persona_id=None)
    if persona_ids:
        Persona.objects.using(db_alias).filter(pk__in=persona_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_seed_contact_labels_and_cleanup_legacy_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('luogo_nascita_custom', models.CharField(blank=True, max_length=160)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('indirizzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persone', to='anagrafica.indirizzo')),
                ('luogo_nascita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persone_nate', to='anagrafica.citta')),
                ('nazionalita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persone_nazionalita', to='anagrafica.nazione')),
                ('nazione_nascita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persone_nate', to='anagrafica.nazione')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persone',
                'db_table': 'anagrafica_persona',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='familiare',
            name='persona',
            field=models.OneToOneField(blank=True, help_text='Anagrafica persona condivisa con eventuali profili lavorativi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profilo_familiare', to='anagrafica.persona'),
        ),
        migrations.RunPython(seed_persone_da_familiari, unseed_persone_da_familiari),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(condition=models.Q(('codice_fiscale', ''), _negated=True), fields=('codice_fiscale',), name='anagrafica_persona_cf_unique'),
        ),
    ]
