# Generated by Django 5.2.13 on 2026-04-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0003_alter_indirizzo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citta',
            name='cap',
        ),
        migrations.CreateModel(
            name='CAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10)),
                ('ordine', models.IntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('citta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_list', to='anagrafica.citta')),
            ],
            options={
                'verbose_name': 'CAP',
                'verbose_name_plural': 'CAP',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='cap_scelto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indirizzi', to='anagrafica.cap'),
        ),
        migrations.AddConstraint(
            model_name='cap',
            constraint=models.UniqueConstraint(fields=('codice', 'citta'), name='unique_cap_citta'),
        ),
    ]
