# Generated by Django 5.2.13 on 2026-05-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0003_persona_familiare_persona_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familiare',
            options={'ordering': ['persona__cognome', 'persona__nome'], 'verbose_name': 'Familiare', 'verbose_name_plural': 'Familiari'},
        ),
        migrations.AlterModelOptions(
            name='studentefamiliare',
            options={'ordering': ['studente__cognome', 'studente__nome', 'familiare__persona__cognome', 'familiare__persona__nome'], 'verbose_name': 'Relazione studente-familiare', 'verbose_name_plural': 'Relazioni studenti-familiari'},
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='attivo',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='codice_fiscale',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='data_nascita',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='email',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='indirizzo',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='luogo_nascita',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='luogo_nascita_custom',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='nazionalita',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='nazione_nascita',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='note',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='sesso',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='telefono',
        ),
    ]
