# Generated by Django 5.2.13 on 2026-05-11 02:12

import django.db.models.deletion
from django.db import migrations, models


def ensure_missing_persona(apps, schema_editor):
    Persona = apps.get_model("anagrafica", "Persona")
    Familiare = apps.get_model("anagrafica", "Familiare")
    db_alias = schema_editor.connection.alias

    for familiare in Familiare.objects.using(db_alias).filter(persona__isnull=True):
        persona = Persona.objects.using(db_alias).create(nome="", cognome="")
        familiare.persona_id = persona.pk
        familiare.save(update_fields=["persona"])


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0004_alter_familiare_options_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_missing_persona, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='familiare',
            name='persona',
            field=models.OneToOneField(help_text='Anagrafica persona condivisa con eventuali profili lavorativi.', on_delete=django.db.models.deletion.CASCADE, related_name='profilo_familiare', to='anagrafica.persona'),
        ),
    ]
