# Generated by Django 5.2.13 on 2026-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0004_remove_citta_cap_cap_indirizzo_cap_scelto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citta',
            name='codice_istat',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
