# Generated by Codex on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0005_citta_codice_istat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regione",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provincia",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="citta",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cap",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statorelazionefamiglia",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="relazionefamiliare",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
