# Generated by Django 5.2.13 on 2026-09-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0006_alter_familiare_relazione_familiare'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='professione',
            field=models.CharField(blank=True, max_length=255, verbose_name='Professione'),
        ),
    ]
