# Generated by Django 5.2.13 on 2026-09-27 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_persona_professione'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndirizzoArchivioMigrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originale_id', models.PositiveBigIntegerField(unique=True)),
                ('canonico_id', models.PositiveBigIntegerField()),
                ('dati', models.JSONField()),
                ('relazioni', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ResidenzaFamiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='familiare',
            name='usa_indirizzo_famiglia',
            field=models.BooleanField(default=False, verbose_name="Usa l'indirizzo principale della famiglia"),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='chiave_normalizzata',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='civico_normalizzato',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='geoapify_place_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='latitudine',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='longitudine',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='via_normalizzata',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='studente',
            name='usa_indirizzo_famiglia',
            field=models.BooleanField(default=False, verbose_name="Usa l'indirizzo principale della famiglia"),
        ),
        migrations.AddIndex(
            model_name='indirizzo',
            index=models.Index(fields=['citta', 'via_normalizzata', 'civico_normalizzato'], name='indirizzo_lookup_idx'),
        ),
        migrations.AddField(
            model_name='residenzafamiglia',
            name='indirizzo_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residenze_famiglie', to='anagrafica.indirizzo'),
        ),
        migrations.AddField(
            model_name='familiare',
            name='residenza_famiglia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familiari', to='anagrafica.residenzafamiglia'),
        ),
        migrations.AddField(
            model_name='studente',
            name='residenza_famiglia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studenti', to='anagrafica.residenzafamiglia'),
        ),
    ]
