# Generated by Django 5.2.13 on 2026-04-29 10:17

import anagrafica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0009_alter_documento_file_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(max_length=255, upload_to=anagrafica.models.documento_upload_to),
        ),
    ]
