# Generated by Django 5.2.13 on 2026-04-30 09:59

import django.db.models.deletion
from django.db import migrations, models


def seed_nazioni(apps, schema_editor):
    Nazione = apps.get_model("anagrafica", "Nazione")
    for data in [
        {
            "nome": "Italia",
            "codice_iso2": "IT",
            "codice_iso3": "ITA",
            "codice_belfiore": "",
            "ordine": 1,
        },
        {
            "nome": "Francia",
            "codice_iso2": "FR",
            "codice_iso3": "FRA",
            "codice_belfiore": "Z110",
            "ordine": 2,
        },
    ]:
        Nazione.objects.update_or_create(
            nome=data["nome"],
            defaults={**data, "attiva": True},
        )


def unseed_nazioni(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0010_alter_documento_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('codice_iso2', models.CharField(blank=True, max_length=2)),
                ('codice_iso3', models.CharField(blank=True, max_length=3)),
                ('codice_belfiore', models.CharField(blank=True, db_index=True, max_length=4)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nazione',
                'verbose_name_plural': 'Nazioni',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='familiare',
            name='luogo_nascita_custom',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='studente',
            name='luogo_nascita_custom',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='familiare',
            name='nazionalita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familiari_nazionalita', to='anagrafica.nazione'),
        ),
        migrations.AddField(
            model_name='familiare',
            name='nazione_nascita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='familiari_nati', to='anagrafica.nazione'),
        ),
        migrations.AddField(
            model_name='studente',
            name='nazionalita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studenti_nazionalita', to='anagrafica.nazione'),
        ),
        migrations.AddField(
            model_name='studente',
            name='nazione_nascita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studenti_nati', to='anagrafica.nazione'),
        ),
        migrations.RunPython(seed_nazioni, unseed_nazioni),
    ]
