# Generated by Django 5.2.13 on 2026-05-08 09:05

import django.db.models.deletion
from django.db import migrations, models


ADDRESS_LABELS = ["Principale", "Residenza", "Domicilio", "Casa", "Lavoro", "Altro"]
PHONE_LABELS = ["Principale", "Cellulare", "Casa", "Lavoro", "Emergenza", "Altro"]
EMAIL_LABELS = ["Principale", "Personale", "Lavoro", "PEC", "Altro"]


def _ensure_labels(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    LabelIndirizzo = apps.get_model("anagrafica", "LabelIndirizzo")
    LabelTelefono = apps.get_model("anagrafica", "LabelTelefono")
    LabelEmail = apps.get_model("anagrafica", "LabelEmail")

    labels = {"indirizzi": {}, "telefoni": {}, "email": {}}
    for index, nome in enumerate(ADDRESS_LABELS, start=1):
        labels["indirizzi"][nome] = LabelIndirizzo.objects.using(db_alias).get_or_create(
            nome=nome,
            defaults={"ordine": index, "attiva": True},
        )[0]
    for index, nome in enumerate(PHONE_LABELS, start=1):
        labels["telefoni"][nome] = LabelTelefono.objects.using(db_alias).get_or_create(
            nome=nome,
            defaults={"ordine": index, "attiva": True},
        )[0]
    for index, nome in enumerate(EMAIL_LABELS, start=1):
        labels["email"][nome] = LabelEmail.objects.using(db_alias).get_or_create(
            nome=nome,
            defaults={"ordine": index, "attiva": True},
        )[0]
    return labels


def _content_type_for(apps, schema_editor, model):
    ContentType = apps.get_model("contenttypes", "ContentType")
    return ContentType.objects.db_manager(schema_editor.connection.alias).get_for_model(model)


def _sync_principal_contacts(apps, schema_editor, instance, *, indirizzo_id=None, telefono="", email=""):
    db_alias = schema_editor.connection.alias
    labels = _ensure_labels(apps, schema_editor)
    AnagraficaIndirizzo = apps.get_model("anagrafica", "AnagraficaIndirizzo")
    AnagraficaTelefono = apps.get_model("anagrafica", "AnagraficaTelefono")
    AnagraficaEmail = apps.get_model("anagrafica", "AnagraficaEmail")
    content_type = _content_type_for(apps, schema_editor, instance.__class__)

    if indirizzo_id:
        AnagraficaIndirizzo.objects.using(db_alias).update_or_create(
            content_type=content_type,
            object_id=instance.pk,
            principale=True,
            defaults={
                "indirizzo_id": indirizzo_id,
                "label": labels["indirizzi"]["Principale"],
                "ordine": 1,
            },
        )
    telefono = (telefono or "").strip()
    if telefono:
        AnagraficaTelefono.objects.using(db_alias).update_or_create(
            content_type=content_type,
            object_id=instance.pk,
            principale=True,
            defaults={
                "numero": telefono,
                "label": labels["telefoni"]["Principale"],
                "ordine": 1,
            },
        )
    email = (email or "").strip().lower()
    if email:
        AnagraficaEmail.objects.using(db_alias).update_or_create(
            content_type=content_type,
            object_id=instance.pk,
            principale=True,
            defaults={
                "email": email,
                "label": labels["email"]["Principale"],
                "ordine": 1,
            },
        )


def seed_anagrafica_contacts(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    _ensure_labels(apps, schema_editor)
    Familiare = apps.get_model("anagrafica", "Familiare")
    Studente = apps.get_model("anagrafica", "Studente")
    StudenteFamiliare = apps.get_model("anagrafica", "StudenteFamiliare")
    Dipendente = apps.get_model("gestione_amministrativa", "Dipendente")

    for familiare in (
        Familiare.objects.using(db_alias)
        .select_related("famiglia", "indirizzo", "famiglia__indirizzo_principale")
        .iterator()
    ):
        indirizzo_id = familiare.indirizzo_id or getattr(familiare.famiglia, "indirizzo_principale_id", None)
        _sync_principal_contacts(
            apps,
            schema_editor,
            familiare,
            indirizzo_id=indirizzo_id,
            telefono=familiare.telefono,
            email=familiare.email,
        )

    for studente in (
        Studente.objects.using(db_alias)
        .select_related("famiglia", "indirizzo", "famiglia__indirizzo_principale")
        .iterator()
    ):
        indirizzo_id = studente.indirizzo_id or getattr(studente.famiglia, "indirizzo_principale_id", None)
        _sync_principal_contacts(apps, schema_editor, studente, indirizzo_id=indirizzo_id)

    for dipendente in Dipendente.objects.using(db_alias).iterator():
        _sync_principal_contacts(
            apps,
            schema_editor,
            dipendente,
            indirizzo_id=dipendente.indirizzo_id,
            telefono=dipendente.telefono,
            email=dipendente.email,
        )

    for studente in Studente.objects.using(db_alias).iterator():
        familiari = Familiare.objects.using(db_alias).filter(famiglia_id=studente.famiglia_id)
        for familiare in familiari:
            StudenteFamiliare.objects.using(db_alias).update_or_create(
                studente_id=studente.pk,
                familiare_id=familiare.pk,
                defaults={
                    "relazione_familiare_id": familiare.relazione_familiare_id,
                    "referente_principale": familiare.referente_principale,
                    "convivente": familiare.convivente,
                    "attivo": familiare.attivo and studente.attivo,
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0012_nazione_nome_nazionalita_belfiore_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestione_amministrativa', '0009_dipendente_gruppo_classe_mansione'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etichetta email',
                'verbose_name_plural': 'Etichette email',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LabelIndirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etichetta indirizzo',
                'verbose_name_plural': 'Etichette indirizzi',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='LabelTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etichetta telefono',
                'verbose_name_plural': 'Etichette telefoni',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='StudenteFamiliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referente_principale', models.BooleanField(default=False)),
                ('convivente', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('familiare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazioni_studenti', to='anagrafica.familiare')),
                ('relazione_familiare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relazioni_studenti', to='anagrafica.relazionefamiliare')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relazioni_familiari', to='anagrafica.studente')),
            ],
            options={
                'verbose_name': 'Relazione studente-familiare',
                'verbose_name_plural': 'Relazioni studenti-familiari',
                'ordering': ['studente__cognome', 'studente__nome', 'familiare__cognome', 'familiare__nome'],
            },
        ),
        migrations.AddField(
            model_name='studente',
            name='familiari',
            field=models.ManyToManyField(blank=True, related_name='studenti_collegati', through='anagrafica.StudenteFamiliare', to='anagrafica.familiare'),
        ),
        migrations.CreateModel(
            name='AnagraficaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('principale', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti', to='anagrafica.labelemail')),
            ],
            options={
                'verbose_name': 'Email anagrafica',
                'verbose_name_plural': 'Email anagrafiche',
                'ordering': ['ordine', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='anag_email_owner_idx'), models.Index(fields=['email'], name='anag_email_value_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principale', True)), fields=('content_type', 'object_id'), name='unique_email_principale')],
            },
        ),
        migrations.CreateModel(
            name='AnagraficaIndirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('principale', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('indirizzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collegamenti_anagrafici', to='anagrafica.indirizzo')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti', to='anagrafica.labelindirizzo')),
            ],
            options={
                'verbose_name': 'Indirizzo anagrafico',
                'verbose_name_plural': 'Indirizzi anagrafici',
                'ordering': ['ordine', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='anag_ind_owner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principale', True)), fields=('content_type', 'object_id'), name='unique_indirizzo_principale')],
            },
        ),
        migrations.CreateModel(
            name='AnagraficaTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('numero', models.CharField(max_length=40)),
                ('principale', models.BooleanField(default=False)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collegamenti', to='anagrafica.labeltelefono')),
            ],
            options={
                'verbose_name': 'Telefono anagrafico',
                'verbose_name_plural': 'Telefoni anagrafici',
                'ordering': ['ordine', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='anag_tel_owner_idx'), models.Index(fields=['numero'], name='anag_tel_numero_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principale', True)), fields=('content_type', 'object_id'), name='unique_telefono_principale')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentefamiliare',
            constraint=models.UniqueConstraint(fields=('studente', 'familiare'), name='unique_studente_familiare'),
        ),
        migrations.RunPython(seed_anagrafica_contacts, noop_reverse),
    ]
