# Generated by Django 5.2.13 on 2026-05-09 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0013_labelemail_labelindirizzo_labeltelefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiare',
            name='famiglia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiari', to='anagrafica.famiglia'),
        ),
        migrations.AlterField(
            model_name='studente',
            name='famiglia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studenti', to='anagrafica.famiglia'),
        ),
    ]
