# Generated by Django 5.2.13 on 2026-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0014_alter_familiare_famiglia_alter_studente_famiglia'),
        ('economia', '0016_alter_scambioretta_options_and_more'),
        ('famiglie_interessate', '0003_remove_famigliainteressata_convertita_in_famiglia'),
        ('servizi_extra', '0002_remove_rataservizioextra_famiglia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famiglia',
            name='indirizzo_principale',
        ),
        migrations.RemoveField(
            model_name='famiglia',
            name='stato_relazione_famiglia',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='famiglia',
        ),
        migrations.RemoveField(
            model_name='familiare',
            name='famiglia',
        ),
        migrations.RemoveField(
            model_name='studente',
            name='famiglia',
        ),
        migrations.DeleteModel(
            name='StatoRelazioneFamiglia',
        ),
        migrations.DeleteModel(
            name='Famiglia',
        ),
    ]
