# Generated by Django 5.2.13 on 2026-04-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafica", "0005_citta_codice_istat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scuola",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_scuola", models.CharField(max_length=200)),
                ("ragione_sociale", models.CharField(blank=True, max_length=200)),
                ("indirizzo_operativo_diverso", models.BooleanField(default=False)),
                ("codice_fiscale", models.CharField(blank=True, max_length=16)),
                ("partita_iva", models.CharField(blank=True, max_length=11)),
                ("sito_web", models.URLField(blank=True)),
                ("note", models.TextField(blank=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_aggiornamento", models.DateTimeField(auto_now=True)),
                ("indirizzo_operativo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scuole_sede_operativa", to="anagrafica.indirizzo")),
                ("indirizzo_sede_legale", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scuole_sede_legale", to="anagrafica.indirizzo")),
            ],
            options={
                "db_table": "sistema_scuola",
                "verbose_name": "Scuola",
                "verbose_name_plural": "Scuola",
                "ordering": ["nome_scuola"],
            },
        ),
        migrations.CreateModel(
            name="ScuolaSocial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_social", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("ordine", models.IntegerField(default=0)),
                ("scuola", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="socials", to="sistema.scuola")),
            ],
            options={
                "db_table": "sistema_scuola_social",
                "verbose_name": "Social scuola",
                "verbose_name_plural": "Social scuola",
                "ordering": ["ordine", "nome_social"],
            },
        ),
    ]
