# Generated by Codex on 2026-04-18

import django.db.models.deletion
from django.db import migrations, models


CREATE_TELEFONO_TABLE = """
CREATE TABLE IF NOT EXISTS sistema_scuola_telefono (
    id bigserial PRIMARY KEY,
    descrizione varchar(100) NOT NULL,
    telefono varchar(30) NOT NULL,
    ordine integer NOT NULL DEFAULT 0,
    scuola_id bigint NOT NULL REFERENCES sistema_scuola(id) DEFERRABLE INITIALLY DEFERRED
);
"""


CREATE_EMAIL_TABLE = """
CREATE TABLE IF NOT EXISTS sistema_scuola_email (
    id bigserial PRIMARY KEY,
    descrizione varchar(100) NOT NULL,
    email varchar(254) NOT NULL,
    ordine integer NOT NULL DEFAULT 0,
    scuola_id bigint NOT NULL REFERENCES sistema_scuola(id) DEFERRABLE INITIALLY DEFERRED
);
"""


ADD_OPERATIVO_DIVERSO_COLUMN = """
ALTER TABLE sistema_scuola
ADD COLUMN IF NOT EXISTS indirizzo_operativo_diverso boolean NOT NULL DEFAULT false;
"""


COPY_OLD_PHONE_EMAIL_DATA = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'sistema_scuola'
          AND column_name = 'telefono_principale'
    ) THEN
        INSERT INTO sistema_scuola_telefono (descrizione, telefono, ordine, scuola_id)
        SELECT 'Principale', telefono_principale, 0, id
        FROM sistema_scuola
        WHERE coalesce(trim(telefono_principale), '') <> ''
          AND NOT EXISTS (
              SELECT 1
              FROM sistema_scuola_telefono t
              WHERE t.scuola_id = sistema_scuola.id
                AND t.descrizione = 'Principale'
                AND t.telefono = sistema_scuola.telefono_principale
          );
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'sistema_scuola'
          AND column_name = 'telefono_secondario'
    ) THEN
        INSERT INTO sistema_scuola_telefono (descrizione, telefono, ordine, scuola_id)
        SELECT 'Secondario', telefono_secondario, 1, id
        FROM sistema_scuola
        WHERE coalesce(trim(telefono_secondario), '') <> ''
          AND NOT EXISTS (
              SELECT 1
              FROM sistema_scuola_telefono t
              WHERE t.scuola_id = sistema_scuola.id
                AND t.descrizione = 'Secondario'
                AND t.telefono = sistema_scuola.telefono_secondario
          );
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'sistema_scuola'
          AND column_name = 'email_principale'
    ) THEN
        INSERT INTO sistema_scuola_email (descrizione, email, ordine, scuola_id)
        SELECT 'Principale', email_principale, 0, id
        FROM sistema_scuola
        WHERE coalesce(trim(email_principale), '') <> ''
          AND NOT EXISTS (
              SELECT 1
              FROM sistema_scuola_email e
              WHERE e.scuola_id = sistema_scuola.id
                AND e.descrizione = 'Principale'
                AND e.email = sistema_scuola.email_principale
          );
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(ADD_OPERATIVO_DIVERSO_COLUMN, reverse_sql=migrations.RunSQL.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_TELEFONO_TABLE, reverse_sql="DROP TABLE IF EXISTS sistema_scuola_telefono;"),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ScuolaTelefono",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("descrizione", models.CharField(max_length=100)),
                        ("telefono", models.CharField(max_length=30)),
                        ("ordine", models.IntegerField(blank=True, null=True)),
                        ("scuola", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="telefoni", to="sistema.scuola")),
                    ],
                    options={
                        "db_table": "sistema_scuola_telefono",
                        "verbose_name": "Telefono scuola",
                        "verbose_name_plural": "Telefoni scuola",
                        "ordering": ["ordine", "descrizione"],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_EMAIL_TABLE, reverse_sql="DROP TABLE IF EXISTS sistema_scuola_email;"),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ScuolaEmail",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("descrizione", models.CharField(max_length=100)),
                        ("email", models.EmailField(max_length=254)),
                        ("ordine", models.IntegerField(blank=True, null=True)),
                        ("scuola", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email", to="sistema.scuola")),
                    ],
                    options={
                        "db_table": "sistema_scuola_email",
                        "verbose_name": "Email scuola",
                        "verbose_name_plural": "Email scuola",
                        "ordering": ["ordine", "descrizione"],
                    },
                ),
            ],
        ),
        migrations.RunSQL(COPY_OLD_PHONE_EMAIL_DATA, reverse_sql=migrations.RunSQL.noop),
    ]
