# Generated by Codex on 2026-04-18

from django.db import migrations, models


DROP_LEGACY_COLUMNS = """
ALTER TABLE sistema_scuola DROP COLUMN IF EXISTS telefono_principale;
ALTER TABLE sistema_scuola DROP COLUMN IF EXISTS telefono_secondario;
ALTER TABLE sistema_scuola DROP COLUMN IF EXISTS email_principale;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0002_scuola_contatti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scuolasocial",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scuolatelefono",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scuolaemail",
            name="ordine",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(DROP_LEGACY_COLUMNS, reverse_sql=migrations.RunSQL.noop),
    ]
