# Generated by Django 5.2.13 on 2026-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_seed_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='interfaccia_colorata_attiva',
            field=models.BooleanField(default=True, help_text="Quando attiva usa accenti colore morbidi per differenziare moduli, icone e azioni principali. Disattivala per un'interfaccia piu uniforme."),
        ),
    ]
