# Generated by Django 5.2.13 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0003_sistemaimpostazionigenerali_interfaccia_colorata_attiva"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistemaimpostazionigenerali",
            name="stile_streamline_attivo",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Quando attivo usa icone emozionali multicolore per dashboard, riepiloghi e intestazioni. "
                    "Le icone funzionali di menu, pulsanti, tabelle e form restano lineari."
                ),
            ),
        ),
    ]
