# Generated by Django 5.2.13 on 2026-04-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0003_cleanup_scuola_legacy_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SistemaUtentePermessi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permesso_anagrafica", models.CharField(choices=[("view", "Sola visualizzazione"), ("manage", "Anche gestione")], default="view", max_length=10)),
                ("permesso_economia", models.CharField(choices=[("view", "Sola visualizzazione"), ("manage", "Anche gestione")], default="view", max_length=10)),
                ("permesso_sistema", models.CharField(choices=[("view", "Sola visualizzazione"), ("manage", "Anche gestione")], default="view", max_length=10)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_aggiornamento", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profilo_permessi", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "sistema_utente_permessi",
                "verbose_name": "Permessi utente",
                "verbose_name_plural": "Permessi utenti",
                "ordering": ["user__last_name", "user__first_name", "user__email"],
            },
        ),
    ]
