# Generated by Django 5.2.13 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0004_sistemautentepermessi"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistemautentepermessi",
            name="ruolo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("amministratore", "Amministratore"),
                    ("segreteria_amministrativa", "Segreteria Amministrativa"),
                    ("segreteria_didattica", "Segreteria Didattica"),
                    ("insegnante", "Insegnante"),
                    ("membro_cda", "Membro del CDA"),
                    ("visualizzatore", "Visualizzatore"),
                ],
                help_text="Ruolo operativo della persona che utilizza l'account.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sistemautentepermessi",
            name="controllo_completo",
            field=models.BooleanField(
                default=False,
                help_text="Permette all'utente di accedere e gestire tutte le sezioni del software senza essere superuser Django.",
            ),
        ),
    ]
