# Generated by Django 5.2.13 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0005_sistemautentepermessi_controllo_completo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistemautentepermessi",
            name="ruolo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("amministratore", "Amministratore"),
                    ("segreteria_amministrativa", "Segreteria Amministrativa"),
                    ("segreteria_didattica", "Segreteria Didattica"),
                    ("insegnante", "Insegnante"),
                    ("membro_cda", "Membro del CDA"),
                    ("visualizzatore", "Visualizzatore"),
                ],
                help_text="Ruolo operativo della persona che utilizza l'account.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sistemautentepermessi",
            name="permesso_calendario",
            field=models.CharField(
                choices=[("view", "Sola visualizzazione"), ("manage", "Anche gestione")],
                default="view",
                max_length=10,
            ),
        ),
    ]
