# Generated by Django 5.2.13 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0006_sistemautentepermessi_permesso_calendario"),
    ]

    operations = [
        migrations.CreateModel(
            name="SistemaImpostazioniGenerali",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "terminologia_studente",
                    models.CharField(
                        choices=[
                            ("studente", "STUDENTE"),
                            ("alunno", "ALUNNO"),
                            ("bambino", "BAMBINO"),
                        ],
                        default="studente",
                        help_text=(
                            "Scegli il termine da visualizzare nel software per riferirti agli studenti. "
                            "La modifica agisce solo sulle etichette mostrate a video."
                        ),
                        max_length=20,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_aggiornamento", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sistema_impostazioni_generali",
                "verbose_name": "Impostazioni generali",
                "verbose_name_plural": "Impostazioni generali",
                "ordering": ["id"],
            },
        ),
    ]
