# Generated by Django 5.2.13 on 2026-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_sistemaimpostazionigenerali'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_account_email',
            field=models.EmailField(blank=True, help_text='Account Google attualmente collegato per la sincronizzazione del calendario.', max_length=254),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_calendar_id',
            field=models.CharField(blank=True, default='primary', help_text="Identificativo del calendario Google da sincronizzare. Lascia 'primary' per il calendario principale.", max_length=255),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_client_id',
            field=models.CharField(blank=True, help_text='Client ID OAuth 2.0 del progetto Google Cloud usato per collegare Google Calendar.', max_length=255),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_client_secret',
            field=models.CharField(blank=True, help_text='Client secret OAuth 2.0 associato al Client ID configurato per Google Calendar.', max_length=255),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_last_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='google_calendar_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
