# Generated by Django 5.2.13 on 2026-05-17 10:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_sidebarpersonalizzazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneEmailSMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('sicurezza', models.CharField(choices=[('none', 'Nessuna'), ('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=16)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('email_mittente', models.EmailField(blank=True, max_length=254)),
                ('nome_mittente', models.CharField(blank=True, default='Arboris', max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('timeout_secondi', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione email SMTP',
                'verbose_name_plural': 'Configurazioni email SMTP',
                'db_table': 'sistema_configurazione_email_smtp',
            },
        ),
        migrations.CreateModel(
            name='ComunicazioneFamigliaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('inviata', 'Inviata'), ('parziale', 'Parziale'), ('errore', 'Errore')], default='inviata', max_length=16)),
                ('oggetto', models.CharField(max_length=255)),
                ('messaggio', models.TextField()),
                ('anni_scolastici', models.JSONField(blank=True, default=list)),
                ('destinatari_selezionati', models.PositiveIntegerField(default=0)),
                ('destinatari_unici', models.PositiveIntegerField(default=0)),
                ('inviate', models.PositiveIntegerField(default=0)),
                ('fallite', models.PositiveIntegerField(default=0)),
                ('duplicati_saltati', models.PositiveIntegerField(default=0)),
                ('dettagli_destinatari', models.JSONField(blank=True, default=list)),
                ('errore_generale', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicazioni_famiglie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log comunicazione famiglie',
                'verbose_name_plural': 'Log comunicazioni famiglie',
                'db_table': 'sistema_comunicazione_famiglia_log',
                'ordering': ['-data_creazione', '-id'],
            },
        ),
    ]
