# Generated by Django 5.2.13 on 2026-04-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0008_sistemaimpostazionigenerali_google_calendar_access_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_access_token",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_account_email",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_calendar_id",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_client_id",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_client_secret",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_last_sync_at",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_last_sync_error",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_refresh_token",
        ),
        migrations.RemoveField(
            model_name="sistemaimpostazionigenerali",
            name="google_calendar_token_expiry",
        ),
    ]
