# Generated by Django 5.2.13 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0009_remove_google_calendar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistemaimpostazionigenerali",
            name="mostra_dashboard_prossimo_anno_scolastico",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Quando attiva, la dashboard mostra anche i riepiloghi generali ed economici "
                    "del prossimo anno scolastico configurato."
                ),
            ),
        ),
    ]
