# Generated by Django 5.2.13 on 2026-09-09 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_sistemaruolopermessi_voci_menu_disabilitate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaLogStatoLettura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storico_fino_id', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stato_lettura_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stato lettura LOG',
            },
        ),
        migrations.CreateModel(
            name='SistemaLogLettura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letta_il', models.DateTimeField(auto_now_add=True)),
                ('operazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture_log', to='sistema.sistemaoperazionecronologia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lettura LOG',
                'constraints': [models.UniqueConstraint(fields=('user', 'operazione'), name='sistema_log_lettura_unica')],
            },
        ),
    ]
