# Generated by Django 5.2.13 on 2026-04-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0010_sistemaimpostazionigenerali_mostra_dashboard_prossimo_anno_scolastico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SistemaBackupDatabaseConfigurazione",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "frequenza_backup_automatico",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Disattivato"),
                            ("giornaliero", "Giornaliero"),
                            ("settimanale", "Settimanale"),
                            ("mensile", "Mensile"),
                        ],
                        default="",
                        help_text="Scegli la frequenza con cui il sistema deve generare automaticamente i backup del database.",
                        max_length=20,
                    ),
                ),
                ("ultimo_backup_automatico_at", models.DateTimeField(blank=True, null=True)),
                ("ultimo_errore_backup_automatico", models.TextField(blank=True)),
                ("backup_automatico_in_corso", models.BooleanField(default=False)),
                ("backup_automatico_avviato_at", models.DateTimeField(blank=True, null=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                ("data_aggiornamento", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configurazione backup database",
                "verbose_name_plural": "Configurazioni backup database",
                "db_table": "sistema_backup_database_configurazione",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SistemaDatabaseBackup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tipo_backup",
                    models.CharField(
                        choices=[
                            ("manuale", "Manuale"),
                            ("automatico", "Automatico"),
                            ("sicurezza_ripristino", "Sicurezza pre-ripristino"),
                        ],
                        default="manuale",
                        max_length=30,
                    ),
                ),
                ("file_backup", models.FileField(upload_to="database_backups/%Y/%m")),
                ("nome_file", models.CharField(max_length=255)),
                ("dimensione_file_bytes", models.BigIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "creato_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_database_creati",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup database",
                "verbose_name_plural": "Backup database",
                "db_table": "sistema_database_backup",
                "ordering": ["-data_creazione", "-id"],
            },
        ),
    ]
