# Generated by Django 5.2.13 on 2026-09-13 23:08

from django.db import migrations, models


def preserve_existing_access(apps, schema_editor):
    alias = schema_editor.connection.alias
    Role = apps.get_model("sistema", "SistemaRuoloPermessi")
    Profile = apps.get_model("sistema", "SistemaUtentePermessi")
    previous_access = models.Q(controllo_completo=True) | models.Q(permesso_economia="manage")
    Role.objects.using(alias).filter(previous_access).update(accesso_comunicazioni_famiglie=True)
    Profile.objects.using(alias).filter(ruolo_permessi__isnull=True).filter(previous_access).update(
        accesso_comunicazioni_famiglie=True,
    )
    enabled_roles = Role.objects.using(alias).filter(accesso_comunicazioni_famiglie=True).values("pk")
    Profile.objects.using(alias).filter(ruolo_permessi_id__in=enabled_roles).update(
        accesso_comunicazioni_famiglie=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_cronologia_login_visualizzazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaruolopermessi',
            name='accesso_comunicazioni_famiglie',
            field=models.BooleanField(default=False, help_text='Consente di preparare e inviare comunicazioni e consultare lo storico, indipendentemente dai permessi dei moduli Anagrafica ed Economia.', verbose_name='Comunicazioni alle famiglie'),
        ),
        migrations.AddField(
            model_name='sistemautentepermessi',
            name='accesso_comunicazioni_famiglie',
            field=models.BooleanField(default=False, verbose_name='Comunicazioni alle famiglie'),
        ),
        migrations.RunPython(preserve_existing_access, migrations.RunPython.noop),
    ]
