# Generated by Django 5.2.13 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0011_sistemabackupdatabaseconfigurazione_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistemaimpostazionigenerali",
            name="font_principale",
            field=models.CharField(
                choices=[
                    ("manrope", "Manrope"),
                    ("dm_sans", "DM Sans"),
                    ("inter", "Inter"),
                    ("nunito_sans", "Nunito Sans"),
                    ("plus_jakarta_sans", "Plus Jakarta Sans"),
                    ("poppins", "Poppins"),
                    ("work_sans", "Work Sans"),
                    ("source_sans_3", "Source Sans 3"),
                    ("outfit", "Outfit"),
                    ("rubik", "Rubik"),
                ],
                default="manrope",
                help_text="Scegli il font Google da usare per il testo principale del software.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="sistemaimpostazionigenerali",
            name="font_titoli",
            field=models.CharField(
                choices=[
                    ("manrope", "Manrope"),
                    ("dm_sans", "DM Sans"),
                    ("inter", "Inter"),
                    ("nunito_sans", "Nunito Sans"),
                    ("plus_jakarta_sans", "Plus Jakarta Sans"),
                    ("poppins", "Poppins"),
                    ("work_sans", "Work Sans"),
                    ("source_sans_3", "Source Sans 3"),
                    ("outfit", "Outfit"),
                    ("rubik", "Rubik"),
                ],
                default="manrope",
                help_text="Scegli il font Google da usare per titoli, intestazioni e sezioni del software.",
                max_length=40,
            ),
        ),
    ]
