# Generated by Django 5.2.13 on 2026-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_sistemaoperazionecronologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemautentepermessi',
            name='permesso_gestione_finanziaria',
            field=models.CharField(choices=[('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='sistemaoperazionecronologia',
            name='modulo',
            field=models.CharField(choices=[('anagrafica', 'Anagrafica'), ('economia', 'Economia'), ('scuola', 'Scuola'), ('calendario', 'Calendario'), ('gestione_finanziaria', 'Gestione finanziaria'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
    ]
