# Generated by Django 5.2.13 on 2026-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_sistemautentepermessi_permesso_servizi_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemautentepermessi',
            name='permesso_gestione_amministrativa',
            field=models.CharField(choices=[('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='sistemaoperazionecronologia',
            name='modulo',
            field=models.CharField(choices=[('anagrafica', 'Anagrafica'), ('economia', 'Economia'), ('scuola', 'Scuola'), ('calendario', 'Calendario'), ('servizi_extra', 'Servizi extra'), ('gestione_finanziaria', 'Gestione finanziaria'), ('gestione_amministrativa', 'Gestione amministrativa'), ('sistema', 'Sistema')], default='sistema', max_length=30),
        ),
    ]
