# Generated by Django 5.2.13 on 2026-04-27 22:29

import django.db.models.deletion
from django.db import migrations, models


PERMISSION_FIELDS = (
    "permesso_anagrafica",
    "permesso_economia",
    "permesso_sistema",
    "permesso_calendario",
    "permesso_gestione_finanziaria",
    "permesso_gestione_amministrativa",
    "permesso_servizi_extra",
)


DEFAULT_ROLES = (
    {
        "key": "amministratore",
        "name": "Amministratore",
        "color": "#417690",
        "amministratore_operativo": True,
        "accesso_backup_database": True,
        "controllo_completo": True,
        "permissions": {field: "manage" for field in PERMISSION_FIELDS},
    },
    {
        "key": "segreteria_amministrativa",
        "name": "Segreteria Amministrativa",
        "color": "#2f855a",
        "amministratore_operativo": False,
        "accesso_backup_database": False,
        "controllo_completo": False,
        "permissions": {
            "permesso_anagrafica": "manage",
            "permesso_economia": "manage",
            "permesso_sistema": "view",
            "permesso_calendario": "manage",
            "permesso_gestione_finanziaria": "manage",
            "permesso_gestione_amministrativa": "view",
            "permesso_servizi_extra": "manage",
        },
    },
    {
        "key": "segreteria_didattica",
        "name": "Segreteria Didattica",
        "color": "#7c3aed",
        "amministratore_operativo": False,
        "accesso_backup_database": False,
        "controllo_completo": False,
        "permissions": {
            "permesso_anagrafica": "manage",
            "permesso_economia": "view",
            "permesso_sistema": "none",
            "permesso_calendario": "manage",
            "permesso_gestione_finanziaria": "none",
            "permesso_gestione_amministrativa": "none",
            "permesso_servizi_extra": "manage",
        },
    },
    {
        "key": "insegnante",
        "name": "Insegnante",
        "color": "#b7791f",
        "amministratore_operativo": False,
        "accesso_backup_database": False,
        "controllo_completo": False,
        "permissions": {
            "permesso_anagrafica": "view",
            "permesso_economia": "none",
            "permesso_sistema": "none",
            "permesso_calendario": "view",
            "permesso_gestione_finanziaria": "none",
            "permesso_gestione_amministrativa": "none",
            "permesso_servizi_extra": "view",
        },
    },
    {
        "key": "membro_cda",
        "name": "Membro del CDA",
        "color": "#0f766e",
        "amministratore_operativo": False,
        "accesso_backup_database": False,
        "controllo_completo": False,
        "permissions": {
            "permesso_anagrafica": "view",
            "permesso_economia": "view",
            "permesso_sistema": "view",
            "permesso_calendario": "view",
            "permesso_gestione_finanziaria": "view",
            "permesso_gestione_amministrativa": "view",
            "permesso_servizi_extra": "view",
        },
    },
    {
        "key": "visualizzatore",
        "name": "Visualizzatore",
        "color": "#64748b",
        "amministratore_operativo": False,
        "accesso_backup_database": False,
        "controllo_completo": False,
        "permissions": {
            "permesso_anagrafica": "view",
            "permesso_economia": "view",
            "permesso_sistema": "none",
            "permesso_calendario": "view",
            "permesso_gestione_finanziaria": "view",
            "permesso_gestione_amministrativa": "none",
            "permesso_servizi_extra": "view",
        },
    },
)


def role_signature_from_values(controllo_completo, values):
    return (
        bool(controllo_completo),
        tuple(values.get(field, "none") for field in PERMISSION_FIELDS),
    )


def default_role_defaults(config):
    defaults = {
        "nome": config["name"],
        "descrizione": "Ruolo creato automaticamente dalla migrazione dei permessi utente.",
        "colore_principale": config["color"],
        "attivo": True,
        "amministratore_operativo": config["amministratore_operativo"],
        "accesso_backup_database": config["accesso_backup_database"],
        "controllo_completo": config["controllo_completo"],
    }
    defaults.update(config["permissions"])
    return defaults


def create_roles_and_assign_profiles(apps, _schema_editor):
    SistemaRuoloPermessi = apps.get_model("sistema", "SistemaRuoloPermessi")
    SistemaUtentePermessi = apps.get_model("sistema", "SistemaUtentePermessi")

    default_roles_by_key = {}
    default_signatures = {}
    used_names = set(SistemaRuoloPermessi.objects.values_list("nome", flat=True))

    for config in DEFAULT_ROLES:
        defaults = default_role_defaults(config)
        role, _created = SistemaRuoloPermessi.objects.update_or_create(
            chiave_legacy=config["key"],
            defaults=defaults,
        )
        default_roles_by_key[config["key"]] = role
        default_signatures[config["key"]] = role_signature_from_values(
            defaults["controllo_completo"],
            defaults,
        )
        used_names.add(role.nome)

    migrated_roles_by_signature = {}
    for profile in SistemaUtentePermessi.objects.all().order_by("id"):
        legacy_key = profile.ruolo or "visualizzatore"
        profile_values = {field: getattr(profile, field, "none") for field in PERMISSION_FIELDS}
        profile_signature = role_signature_from_values(profile.controllo_completo, profile_values)

        if legacy_key in default_roles_by_key and profile_signature == default_signatures[legacy_key]:
            role = default_roles_by_key[legacy_key]
        else:
            cache_key = (legacy_key, profile_signature)
            role = migrated_roles_by_signature.get(cache_key)
            if role is None:
                base_name = default_roles_by_key.get(legacy_key).nome if legacy_key in default_roles_by_key else "Ruolo"
                counter = 1
                name = f"{base_name} - profilo migrato"
                while name in used_names:
                    counter += 1
                    name = f"{base_name} - profilo migrato {counter}"
                used_names.add(name)
                role_defaults = {
                    "nome": name,
                    "descrizione": "Ruolo creato automaticamente per conservare i permessi specifici di un utente esistente.",
                    "colore_principale": default_roles_by_key.get(legacy_key, default_roles_by_key["visualizzatore"]).colore_principale,
                    "attivo": True,
                    "amministratore_operativo": legacy_key == "amministratore",
                    "accesso_backup_database": legacy_key == "amministratore",
                    "controllo_completo": profile.controllo_completo,
                }
                role_defaults.update(profile_values)
                role = SistemaRuoloPermessi.objects.create(**role_defaults)
                migrated_roles_by_signature[cache_key] = role

        profile.ruolo_permessi_id = role.pk
        profile.save(update_fields=["ruolo_permessi"])


def clear_role_assignments(apps, _schema_editor):
    SistemaUtentePermessi = apps.get_model("sistema", "SistemaUtentePermessi")
    SistemaUtentePermessi.objects.update(ruolo_permessi=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_sistemaimpostazionigenerali_osservazioni'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaRuoloPermessi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('chiave_legacy', models.CharField(blank=True, choices=[('amministratore', 'Amministratore'), ('segreteria_amministrativa', 'Segreteria Amministrativa'), ('segreteria_didattica', 'Segreteria Didattica'), ('insegnante', 'Insegnante'), ('membro_cda', 'Membro del CDA'), ('visualizzatore', 'Visualizzatore')], max_length=120, null=True, unique=True)),
                ('colore_principale', models.CharField(default='#417690', max_length=7)),
                ('attivo', models.BooleanField(default=True)),
                ('amministratore_operativo', models.BooleanField(default=False, help_text="Consente l'accesso alle funzioni amministrative operative del sistema.")),
                ('accesso_backup_database', models.BooleanField(default=False, help_text="Consente l'accesso alla pagina Backup Database.")),
                ('controllo_completo', models.BooleanField(default=False, help_text='Permette agli utenti con questo ruolo di accedere e gestire tutte le sezioni del software.')),
                ('permesso_anagrafica', models.CharField(choices=[('none', 'Nessun accesso'), ('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='none', max_length=10)),
                ('permesso_economia', models.CharField(choices=[('none', 'Nessun accesso'), ('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='none', max_length=10)),
                ('permesso_sistema', models.CharField(choices=[('none', 'Nessun accesso'), ('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='none', max_length=10)),
                ('permesso_calendario', models.CharField(choices=[('none', 'Nessun accesso'), ('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='none', max_length=10)),
                ('permesso_gestione_finanziaria', models.CharField(choices=[('none', 'Nessun accesso'), ('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='none', max_length=10)),
                ('permesso_gestione_amministrativa', models.CharField(choices=[('none', 'Nessun accesso'), ('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='none', max_length=10)),
                ('permesso_servizi_extra', models.CharField(choices=[('none', 'Nessun accesso'), ('view', 'Sola visualizzazione'), ('manage', 'Anche gestione')], default='none', max_length=10)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruolo e permessi',
                'verbose_name_plural': 'Ruoli e permessi',
                'db_table': 'sistema_ruolo_permessi',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='sistemautentepermessi',
            name='ruolo_permessi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utenti', to='sistema.sistemaruolopermessi'),
        ),
        migrations.RunPython(create_roles_and_assign_profiles, clear_role_assignments),
    ]
