# Generated by Django 5.2.13 on 2026-04-28 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_sistemaruolopermessi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='gestione_iscrizione_corso_anno',
            field=models.CharField(choices=[('mese_iscrizione_intero', 'Mese di iscrizione incluso per intero'), ('mese_successivo_dopo_soglia', 'Mese successivo dopo soglia'), ('pro_rata_giornaliero', 'Pro-rata giornaliero')], default='mese_iscrizione_intero', help_text='Definisce come calcolare le rette quando lo studente viene iscritto dopo il mese iniziale previsto dalla condizione di iscrizione.', max_length=40),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='giorno_soglia_iscrizione_corso_anno',
            field=models.PositiveSmallIntegerField(default=15, help_text="Usato solo con la regola 'mese successivo dopo soglia': se l'iscrizione avviene dopo questo giorno, la prima retta parte dal mese successivo.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
