# Generated by Django 5.2.13 on 2026-05-03 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_sistemaoperazionecronologia_audit_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSegnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bug', 'Segnalazione bug'), ('funzione', 'Suggerimento funzione')], db_index=True, max_length=20)),
                ('stato', models.CharField(choices=[('nuova', 'Nuova'), ('letta', 'Letta'), ('archiviata', 'Archiviata')], db_index=True, default='nuova', max_length=20)),
                ('messaggio', models.TextField()),
                ('utente_nome', models.CharField(blank=True, max_length=255)),
                ('utente_email', models.EmailField(blank=True, max_length=254)),
                ('utente_ruolo', models.CharField(blank=True, max_length=255)),
                ('pagina_url', models.TextField(blank=True)),
                ('pagina_path', models.CharField(blank=True, max_length=700)),
                ('pagina_titolo', models.CharField(blank=True, max_length=255)),
                ('breadcrumb', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email_destinatario', models.EmailField(default='gliptica.software@gmail.com', max_length=254)),
                ('email_inviata_at', models.DateTimeField(blank=True, null=True)),
                ('email_errore', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_segnalazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback beta',
                'verbose_name_plural': 'Feedback beta',
                'db_table': 'sistema_feedback_segnalazione',
                'ordering': ['-data_creazione', '-id'],
                'indexes': [models.Index(fields=['tipo', 'data_creazione'], name='sistema_feedback_tipo_idx'), models.Index(fields=['stato', 'data_creazione'], name='sistema_feedback_stato_idx')],
            },
        ),
    ]
