# Generated by Django 5.2.13 on 2026-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0027_alter_sistemaoperazionecronologia_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='modulo_anagrafica_attivo',
            field=models.BooleanField(default=True, help_text='Attiva o disattiva globalmente il modulo Anagrafica.'),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='modulo_calendario_attivo',
            field=models.BooleanField(default=True, help_text='Attiva o disattiva globalmente il modulo Calendario.'),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='modulo_economia_attivo',
            field=models.BooleanField(default=True, help_text='Attiva o disattiva globalmente il modulo Economia.'),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='modulo_famiglie_interessate_attivo',
            field=models.BooleanField(default=True, help_text='Attiva o disattiva globalmente il modulo Famiglie interessate.'),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='modulo_gestione_amministrativa_attivo',
            field=models.BooleanField(default=True, help_text='Attiva o disattiva globalmente il modulo Dipendenti e collaboratori.'),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='modulo_gestione_finanziaria_attivo',
            field=models.BooleanField(default=True, help_text='Attiva o disattiva globalmente il modulo Gestione finanziaria.'),
        ),
        migrations.AddField(
            model_name='sistemaimpostazionigenerali',
            name='modulo_servizi_extra_attivo',
            field=models.BooleanField(default=True, help_text='Attiva o disattiva globalmente il modulo Servizi extra.'),
        ),
    ]
