# Generated by Django 5.2.13 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0028_sistemaimpostazionigenerali_modulo_anagrafica_attivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sistemaimpostazionigenerali",
            name="cronologia_retention_mesi",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (6, "6 mesi"),
                    (12, "12 mesi"),
                    (24, "24 mesi"),
                    (36, "36 mesi"),
                    (0, "Conserva sempre"),
                ],
                default=24,
                help_text=(
                    "Periodo di conservazione della cronologia operazioni. Le operazioni piu vecchie "
                    "vengono rimosse automaticamente."
                ),
            ),
        ),
    ]
