# Generated by Django 5.2.13 on 2026-04-23 10:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economia', '0010_rataiscrizione_tipo_rata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnessioneBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(help_text="Etichetta descrittiva per riconoscere la connessione (es. 'Banca Sella - Conto operativo').", max_length=150)),
                ('stato', models.CharField(choices=[('attiva', 'Attiva'), ('scaduta', 'Consenso scaduto'), ('revocata', 'Revocata dal titolare'), ('errore', 'In errore')], default='attiva', max_length=20)),
                ('external_institution_id', models.CharField(blank=True, max_length=120)),
                ('external_connection_id', models.CharField(blank=True, max_length=120)),
                ('access_token_cifrato', models.TextField(blank=True, help_text='Token di accesso cifrato. Non mostrare mai in chiaro nelle interfacce.')),
                ('refresh_token_cifrato', models.TextField(blank=True)),
                ('consenso_scadenza', models.DateTimeField(blank=True, null=True)),
                ('ultimo_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_errore', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connessione bancaria',
                'verbose_name_plural': 'Connessioni bancarie',
                'db_table': 'gestione_finanziaria_connessione_bancaria',
                'ordering': ['provider__nome', 'etichetta'],
            },
        ),
        migrations.CreateModel(
            name='ProviderBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('psd2', 'Aggregatore PSD2'), ('import_file', 'Import estratto conto (file)'), ('manuale', 'Inserimento manuale')], default='psd2', max_length=20)),
                ('configurazione', models.JSONField(blank=True, default=dict, help_text='Parametri tecnici di configurazione del provider (base URL, secret reference, ecc.).')),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider bancario',
                'verbose_name_plural': 'Provider bancari',
                'db_table': 'gestione_finanziaria_provider_bancario',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanziaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('spesa', 'Spesa'), ('entrata', 'Entrata'), ('trasferimento', 'Trasferimento')], default='spesa', help_text='Natura della categoria: spesa, entrata o trasferimento fra conti.', max_length=20)),
                ('colore', models.CharField(blank=True, help_text='Colore esadecimale usato nei report e nei grafici (es. #336699).', max_length=20)),
                ('icona', models.CharField(blank=True, max_length=60)),
                ('attiva', models.BooleanField(default=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Categoria padre, per creare una gerarchia (es. Utenze > Luce).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='figli', to='gestione_finanziaria.categoriafinanziaria')),
            ],
            options={
                'verbose_name': 'Categoria finanziaria',
                'verbose_name_plural': 'Categorie finanziarie',
                'db_table': 'gestione_finanziaria_categoria',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conto', models.CharField(help_text="Nome interno del conto, visibile nelle liste (es. 'Conto operativo BNL').", max_length=150)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('intestatario', models.CharField(blank=True, max_length=200)),
                ('banca', models.CharField(blank=True, max_length=150)),
                ('bic', models.CharField(blank=True, max_length=15)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('external_account_id', models.CharField(blank=True, max_length=120)),
                ('attivo', models.BooleanField(default=True)),
                ('saldo_corrente', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ultimo saldo contabile noto. Aggiornato dalle sincronizzazioni.', max_digits=14)),
                ('saldo_corrente_aggiornato_al', models.DateTimeField(blank=True, null=True)),
                ('data_ultima_sincronizzazione', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('connessione', models.ForeignKey(blank=True, help_text='Solo per provider PSD2: riferimento alla connessione/consenso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conti', to='gestione_finanziaria.connessionebancaria')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conti', to='gestione_finanziaria.providerbancario')),
            ],
            options={
                'verbose_name': 'Conto bancario',
                'verbose_name_plural': 'Conti bancari',
                'db_table': 'gestione_finanziaria_conto_bancario',
                'ordering': ['nome_conto'],
            },
        ),
        migrations.AddField(
            model_name='connessionebancaria',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connessioni', to='gestione_finanziaria.providerbancario'),
        ),
        migrations.CreateModel(
            name='RegolaCategorizzazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('priorita', models.IntegerField(default=100, help_text="A parita' di match viene usata la regola con priorita' piu' bassa.")),
                ('condizione_tipo', models.CharField(choices=[('descrizione_contiene', 'Descrizione contiene'), ('controparte_contiene', 'Controparte contiene'), ('iban_controparte_uguale', 'IBAN controparte uguale a'), ('importo_range', 'Importo compreso fra'), ('segno', 'Solo segno')], max_length=30)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('importo_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('importo_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('segno_filtro', models.CharField(blank=True, choices=[('uscita', 'Uscita (importo negativo)'), ('entrata', 'Entrata (importo positivo)')], max_length=10)),
                ('attiva', models.BooleanField(default=True)),
                ('volte_applicata', models.PositiveIntegerField(default=0)),
                ('ultima_applicazione_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria_da_assegnare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regole', to='gestione_finanziaria.categoriafinanziaria')),
            ],
            options={
                'verbose_name': 'Regola di categorizzazione',
                'verbose_name_plural': 'Regole di categorizzazione',
                'db_table': 'gestione_finanziaria_regola_categorizzazione',
                'ordering': ['priorita', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoFinanziario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(choices=[('banca', 'Movimento bancario'), ('import_file', 'Import estratto conto'), ('manuale', 'Inserimento manuale')], default='manuale', max_length=20)),
                ('data_contabile', models.DateField(db_index=True)),
                ('data_valuta', models.DateField(blank=True, null=True)),
                ('importo', models.DecimalField(decimal_places=2, help_text='Negativo per le uscite, positivo per le entrate.', max_digits=14)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('descrizione', models.TextField(blank=True)),
                ('controparte', models.CharField(blank=True, max_length=200)),
                ('iban_controparte', models.CharField(blank=True, max_length=34)),
                ('categorizzazione_automatica', models.BooleanField(default=False, help_text="True se la categoria e' stata assegnata da una regola, False se confermata dall'utente.")),
                ('categorizzato_il', models.DateTimeField(blank=True, null=True)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('hash_deduplica', models.CharField(blank=True, db_index=True, help_text='Hash per riconoscere duplicati negli import file (data+importo+descrizione).', max_length=64)),
                ('incide_su_saldo_banca', models.BooleanField(default=False, help_text='True per movimenti che corrispondono al saldo reale del conto. False per voci gestionali.')),
                ('stato_riconciliazione', models.CharField(choices=[('non_riconciliato', 'Non riconciliato'), ('riconciliato', 'Riconciliato'), ('ignorato', 'Ignorato')], default='non_riconciliato', max_length=25)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='gestione_finanziaria.categoriafinanziaria')),
                ('categorizzato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_categorizzati', to=settings.AUTH_USER_MODEL)),
                ('conto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti', to='gestione_finanziaria.contobancario')),
                ('rata_iscrizione', models.ForeignKey(blank=True, help_text='Rata del modulo Economia eventualmente riconciliata con questo movimento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_finanziari', to='economia.rataiscrizione')),
                ('regola_categorizzazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_categorizzati', to='gestione_finanziaria.regolacategorizzazione')),
            ],
            options={
                'verbose_name': 'Movimento finanziario',
                'verbose_name_plural': 'Movimenti finanziari',
                'db_table': 'gestione_finanziaria_movimento',
                'ordering': ['-data_contabile', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoConto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_riferimento', models.DateTimeField(db_index=True)),
                ('saldo_contabile', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_disponibile', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valuta', models.CharField(default='EUR', max_length=3)),
                ('fonte', models.CharField(choices=[('provider', 'Provider PSD2'), ('import_file', 'Import file'), ('manuale', 'Manuale')], default='provider', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('conto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storico_saldi', to='gestione_finanziaria.contobancario')),
            ],
            options={
                'verbose_name': 'Saldo conto',
                'verbose_name_plural': 'Saldi conto',
                'db_table': 'gestione_finanziaria_saldo_conto',
                'ordering': ['-data_riferimento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SincronizzazioneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operazione', models.CharField(choices=[('sync_saldo', 'Sincronizzazione saldo'), ('sync_movimenti', 'Sincronizzazione movimenti'), ('import_file', 'Import file estratto conto'), ('refresh_consenso', 'Refresh consenso PSD2')], max_length=30)),
                ('esito', models.CharField(choices=[('ok', 'Completata'), ('parziale', 'Parziale'), ('errore', 'Errore')], default='ok', max_length=10)),
                ('movimenti_inseriti', models.PositiveIntegerField(default=0)),
                ('movimenti_aggiornati', models.PositiveIntegerField(default=0)),
                ('durata_millisecondi', models.PositiveIntegerField(blank=True, null=True)),
                ('messaggio', models.TextField(blank=True)),
                ('data_operazione', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connessione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_sincronizzazioni', to='gestione_finanziaria.connessionebancaria')),
                ('conto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_sincronizzazioni', to='gestione_finanziaria.contobancario')),
            ],
            options={
                'verbose_name': 'Log sincronizzazione',
                'verbose_name_plural': 'Log sincronizzazioni',
                'db_table': 'gestione_finanziaria_sincronizzazione_log',
                'ordering': ['-data_operazione', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriafinanziaria',
            constraint=models.UniqueConstraint(fields=('nome', 'parent'), name='gestione_finanziaria_categoria_nome_parent_unique'),
        ),
        migrations.AddIndex(
            model_name='movimentofinanziario',
            index=models.Index(fields=['conto', 'data_contabile'], name='gf_mov_conto_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentofinanziario',
            index=models.Index(fields=['categoria', 'data_contabile'], name='gf_mov_cat_data_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentofinanziario',
            index=models.Index(fields=['stato_riconciliazione'], name='gf_mov_stato_ric_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentofinanziario',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('conto', 'provider_transaction_id'), name='gf_mov_unique_provider_tx_per_conto'),
        ),
        migrations.AddIndex(
            model_name='saldoconto',
            index=models.Index(fields=['conto', 'data_riferimento'], name='gf_saldo_conto_data_idx'),
        ),
    ]
