# Generated by Django 5.2.13 on 2026-05-13 07:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_amministrativa', '0006_dipendente_materia'),
        ('gestione_finanziaria', '0002_seed_bank_providers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoRatealeSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('finanziamento', 'Finanziamento'), ('f24', 'F24 / contributi'), ('fornitore', 'Rateizzazione fornitore'), ('altro', 'Altro piano rateale')], default='finanziamento', max_length=30)),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_rate', models.PositiveSmallIntegerField(default=1)),
                ('frequenza_mesi', models.PositiveSmallIntegerField(default=1)),
                ('data_prima_scadenza', models.DateField(db_index=True)),
                ('giorno_scadenza', models.PositiveSmallIntegerField(blank=True, help_text='Giorno del mese da usare per le rate successive. Se vuoto usa il giorno della prima scadenza.', null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piani_rateali_spesa', to='gestione_finanziaria.categoriafinanziaria')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piani_rateali_spesa_creati', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piani_rateali_spesa', to='gestione_finanziaria.fornitore')),
            ],
            options={
                'verbose_name': 'Piano rateale di spesa',
                'verbose_name_plural': 'Piani rateali di spesa',
                'db_table': 'gestione_finanziaria_piano_rateale_spesa',
                'ordering': ['data_prima_scadenza', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpesaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rata', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('totale_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('manuale', 'Spesa manuale'), ('contanti', 'Contanti'), ('busta_paga', 'Busta paga'), ('f24', 'F24 / contributi'), ('rata_piano', 'Rata piano'), ('finanziamento', 'Finanziamento'), ('altro', 'Altro')], default='manuale', max_length=30)),
                ('descrizione', models.CharField(max_length=220)),
                ('data_scadenza', models.DateField(db_index=True)),
                ('importo_previsto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('importo_pagato', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spese_operative', to='gestione_finanziaria.categoriafinanziaria')),
                ('conto_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_operative', to='gestione_finanziaria.contobancario')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_operative_create', to=settings.AUTH_USER_MODEL)),
                ('dipendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_operative', to='gestione_amministrativa.dipendente')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_operative', to='gestione_finanziaria.fornitore')),
                ('movimento_finanziario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spese_operative', to='gestione_finanziaria.movimentofinanziario')),
                ('piano_rateale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='gestione_finanziaria.pianoratealespesa')),
            ],
            options={
                'verbose_name': 'Spesa operativa',
                'verbose_name_plural': 'Spese operative',
                'db_table': 'gestione_finanziaria_spesa_operativa',
                'ordering': ['data_scadenza', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pianoratealespesa',
            index=models.Index(fields=['data_prima_scadenza', 'attivo'], name='gf_piano_spesa_data_idx'),
        ),
        migrations.AddIndex(
            model_name='pianoratealespesa',
            index=models.Index(fields=['categoria'], name='gf_piano_spesa_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='pianoratealespesa',
            constraint=models.CheckConstraint(condition=models.Q(('importo_totale__gt', 0)), name='gf_piano_spesa_importo_pos'),
        ),
        migrations.AddConstraint(
            model_name='pianoratealespesa',
            constraint=models.CheckConstraint(condition=models.Q(('numero_rate__gt', 0)), name='gf_piano_spesa_rate_pos'),
        ),
        migrations.AddConstraint(
            model_name='pianoratealespesa',
            constraint=models.CheckConstraint(condition=models.Q(('frequenza_mesi__gt', 0)), name='gf_piano_spesa_freq_pos'),
        ),
        migrations.AddIndex(
            model_name='spesaoperativa',
            index=models.Index(fields=['data_scadenza', 'tipo'], name='gf_spesa_op_data_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='spesaoperativa',
            index=models.Index(fields=['categoria', 'data_scadenza'], name='gf_spesa_op_cat_data_idx'),
        ),
        migrations.AddIndex(
            model_name='spesaoperativa',
            index=models.Index(fields=['piano_rateale'], name='gf_spesa_op_piano_idx'),
        ),
        migrations.AddConstraint(
            model_name='spesaoperativa',
            constraint=models.CheckConstraint(condition=models.Q(('importo_previsto__gt', 0)), name='gf_spesa_op_previsto_pos'),
        ),
        migrations.AddConstraint(
            model_name='spesaoperativa',
            constraint=models.CheckConstraint(condition=models.Q(('importo_pagato__gte', 0)), name='gf_spesa_op_pagato_gte0'),
        ),
    ]
