# Generated by Django 5.2.13 on 2026-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0003_seed_provider_gocardless_bad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianificazioneSincronizzazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attivo', models.BooleanField(default=False)),
                ('intervallo_ore', models.PositiveIntegerField(default=12, help_text='Ogni quante ore tentare la sincronizzazione automatica.')),
                ('sync_saldo', models.BooleanField(default=True)),
                ('sync_movimenti', models.BooleanField(default=True)),
                ('giorni_storico', models.PositiveIntegerField(default=14, help_text='Per i movimenti: quanti giorni indietro richiedere ad ogni esecuzione.')),
                ('ultimo_run_at', models.DateTimeField(blank=True, null=True)),
                ('avviato_at', models.DateTimeField(blank=True, null=True)),
                ('in_corso', models.BooleanField(default=False)),
                ('ultimo_esito', models.CharField(blank=True, choices=[('ok', 'Completata'), ('parziale', 'Parziale'), ('errore', 'Errore')], max_length=20)),
                ('ultimo_messaggio', models.TextField(blank=True)),
                ('conti_sincronizzati', models.PositiveIntegerField(default=0)),
                ('conti_in_errore', models.PositiveIntegerField(default=0)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pianificazione sincronizzazione',
                'verbose_name_plural': 'Pianificazione sincronizzazione',
                'db_table': 'gestione_finanziaria_pianificazione_sync',
            },
        ),
    ]
