# Generated by Django 5.2.13 on 2026-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0004_pianificazionesincronizzazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='connessionebancaria',
            name='access_token_scadenza',
            field=models.DateTimeField(blank=True, help_text="Scadenza dell'access token a breve durata (es. OAuth2 TrueLayer: 1h).", null=True),
        ),
        migrations.AlterField(
            model_name='connessionebancaria',
            name='consenso_scadenza',
            field=models.DateTimeField(blank=True, help_text='Scadenza del consenso complessivo (es. 90 giorni PSD2).', null=True),
        ),
    ]
