# Generated by Django 5.2.13 on 2026-04-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0007_seed_provider_saltedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='contobancario',
            name='saldo_ultimo_estratto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Saldo ufficiale dichiarato dalla banca nell'ultimo estratto CAMT.053 importato (tag <Bal> con codice CLBD = Closing Booked). Serve per confronto con il saldo denormalizzato calcolato dai movimenti.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contobancario',
            name='saldo_ultimo_estratto_data',
            field=models.DateField(blank=True, help_text="Data del saldo CLBD dell'ultimo estratto CAMT.053 importato.", null=True),
        ),
        migrations.AlterField(
            model_name='sincronizzazionelog',
            name='tipo_operazione',
            field=models.CharField(choices=[('sync_saldo', 'Sincronizzazione saldo'), ('sync_movimenti', 'Sincronizzazione movimenti'), ('import_file', 'Import file estratto conto'), ('import_sftp', 'Import CAMT da inbox SFTP'), ('refresh_consenso', 'Refresh consenso PSD2')], max_length=30),
        ),
        migrations.CreateModel(
            name='CanaleSftpInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=120)),
                ('tipo_autenticazione', models.CharField(choices=[('password', 'Password'), ('chiave_privata', 'Chiave privata SSH')], default='password', max_length=20)),
                ('password_cifrata', models.TextField(blank=True)),
                ('chiave_privata_pem_cifrata', models.TextField(blank=True)),
                ('chiave_privata_passphrase_cifrata', models.TextField(blank=True)),
                ('host_key_base64', models.TextField(blank=True, help_text="Host key SSH del server remoto in formato 'algoritmo base64_key'. Popolato automaticamente al primo connect (TOFU). Svuota per riacquisirla.")),
                ('remote_path_inbox', models.CharField(help_text="Cartella remota da cui scaricare i CAMT (es. '/out/camt053/').", max_length=512)),
                ('remote_path_processed', models.CharField(blank=True, help_text="Cartella remota dove spostare i file elaborati con successo. Se vuota, i file vengono solo rinominati con suffisso '.elaborato_YYYYMMDDHHMM'.", max_length=512)),
                ('remote_path_errori', models.CharField(blank=True, help_text="Cartella remota dove spostare i file con errori (IBAN mismatch, XML non parsabile, ecc.). Se vuota, vengono rinominati con suffisso '.errore_YYYYMMDDHHMM'.", max_length=512)),
                ('pattern_file', models.CharField(default='*.xml,*.zip', help_text="Pattern glob dei file da considerare, separati da virgola. Default: '*.xml,*.zip'.", max_length=200)),
                ('azione_dopo_import', models.CharField(choices=[('sposta', "Sposta in cartelle 'processed' / 'errors'"), ('rinomina', "Rinomina con suffisso '.elaborato' / '.errore'")], default='sposta', max_length=20)),
                ('attivo', models.BooleanField(default=True)),
                ('data_ultima_esecuzione', models.DateTimeField(blank=True, null=True)),
                ('ultimo_esito', models.CharField(blank=True, choices=[('ok', 'Completata'), ('parziale', 'Parziale'), ('errore', 'Errore')], max_length=10)),
                ('ultimo_messaggio', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('conto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canale_sftp', to='gestione_finanziaria.contobancario')),
            ],
            options={
                'verbose_name': 'Canale SFTP inbox',
                'verbose_name_plural': 'Canali SFTP inbox',
                'db_table': 'gestione_finanziaria_canale_sftp_inbox',
                'ordering': ['conto__nome_conto'],
            },
        ),
    ]
