# Generated by Django 5.2.13 on 2026-04-23 20:54

from django.db import migrations, models


def azzera_tipo_operazione_sftp(apps, schema_editor):
    SincronizzazioneLog = apps.get_model("gestione_finanziaria", "SincronizzazioneLog")
    SincronizzazioneLog.objects.filter(tipo_operazione="import_sftp").update(
        tipo_operazione="import_file"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0008_canale_sftp_inbox'),
    ]

    operations = [
        migrations.RunPython(azzera_tipo_operazione_sftp, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contobancario',
            name='saldo_ultimo_estratto',
        ),
        migrations.RemoveField(
            model_name='contobancario',
            name='saldo_ultimo_estratto_data',
        ),
        migrations.AlterField(
            model_name='sincronizzazionelog',
            name='tipo_operazione',
            field=models.CharField(choices=[('sync_saldo', 'Sincronizzazione saldo'), ('sync_movimenti', 'Sincronizzazione movimenti'), ('import_file', 'Import file estratto conto'), ('refresh_consenso', 'Refresh consenso PSD2')], max_length=30),
        ),
        migrations.DeleteModel(
            name='CanaleSftpInbox',
        ),
    ]
