# Generated by Django 5.2.13 on 2026-04-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0010_seed_provider_enablebanking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connessionebancaria',
            name='external_institution_id',
            field=models.CharField(blank=True, help_text='Id istituto lato provider (es. TrueLayer, o NomeASPSP|IT per Enable Banking).', max_length=512),
        ),
    ]
