# Generated by Django 5.2.13 on 2026-04-27 18:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0011_connessione_institution_id_lungo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('ordine', models.IntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria spesa',
                'verbose_name_plural': 'Categorie spesa',
                'db_table': 'gestione_finanziaria_categoria_spesa',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=220)),
                ('tipo_soggetto', models.CharField(choices=[('azienda', 'Azienda'), ('professionista', 'Professionista'), ('associazione', 'Associazione'), ('persona_fisica', 'Persona fisica'), ('altro', 'Altro')], default='azienda', max_length=30)),
                ('codice_fiscale', models.CharField(blank=True, max_length=16)),
                ('partita_iva', models.CharField(blank=True, max_length=11)),
                ('indirizzo', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pec', models.EmailField(blank=True, max_length=254)),
                ('codice_sdi', models.CharField(blank=True, max_length=7)),
                ('referente', models.CharField(blank=True, max_length=160)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('banca', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria_spesa', models.ForeignKey(blank=True, help_text='Categoria prevalente usata come default sui documenti del fornitore.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fornitori', to='gestione_finanziaria.categoriaspesa')),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'db_table': 'gestione_finanziaria_fornitore',
                'ordering': ['denominazione'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('fattura', 'Fattura'), ('parcella', 'Parcella'), ('ricevuta', 'Ricevuta'), ('nota_credito', 'Nota di credito'), ('altro', 'Altro')], default='fattura', max_length=30)),
                ('numero_documento', models.CharField(max_length=80)),
                ('data_documento', models.DateField(db_index=True)),
                ('data_ricezione', models.DateField(blank=True, null=True)),
                ('anno_competenza', models.PositiveIntegerField(blank=True, null=True)),
                ('mese_competenza', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=255)),
                ('imponibile', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('totale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stato', models.CharField(choices=[('da_pagare', 'Da pagare'), ('parzialmente_pagato', 'Parzialmente pagato'), ('pagato', 'Pagato'), ('annullato', 'Annullato')], default='da_pagare', max_length=30)),
                ('allegato', models.FileField(blank=True, upload_to='gestione_finanziaria/fornitori/%Y/%m/')),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria_spesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documenti_fornitori', to='gestione_finanziaria.categoriaspesa')),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='gestione_finanziaria.fornitore')),
            ],
            options={
                'verbose_name': 'Documento fornitore',
                'verbose_name_plural': 'Documenti fornitori',
                'db_table': 'gestione_finanziaria_documento_fornitore',
                'ordering': ['-data_documento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScadenzaPagamentoFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField(db_index=True)),
                ('importo_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('importo_pagato', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('prevista', 'Prevista'), ('scaduta', 'Scaduta'), ('parzialmente_pagata', 'Parzialmente pagata'), ('pagata', 'Pagata'), ('annullata', 'Annullata')], default='prevista', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('conto_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scadenze_fornitori', to='gestione_finanziaria.contobancario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='gestione_finanziaria.documentofornitore')),
                ('movimento_finanziario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scadenze_fornitori', to='gestione_finanziaria.movimentofinanziario')),
            ],
            options={
                'verbose_name': 'Scadenza pagamento fornitore',
                'verbose_name_plural': 'Scadenze pagamento fornitori',
                'db_table': 'gestione_finanziaria_scadenza_fornitore',
                'ordering': ['data_scadenza', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='documentofornitore',
            index=models.Index(fields=['fornitore', 'data_documento'], name='gf_doc_forn_data_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofornitore',
            index=models.Index(fields=['categoria_spesa', 'data_documento'], name='gf_doc_catsp_data_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofornitore',
            index=models.Index(fields=['stato'], name='gf_doc_forn_stato_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentofornitore',
            constraint=models.UniqueConstraint(fields=('fornitore', 'tipo_documento', 'numero_documento', 'data_documento'), name='gf_doc_forn_unique_numero_data'),
        ),
        migrations.AddIndex(
            model_name='scadenzapagamentofornitore',
            index=models.Index(fields=['data_scadenza', 'stato'], name='gf_scad_forn_data_stato_idx'),
        ),
        migrations.AddIndex(
            model_name='scadenzapagamentofornitore',
            index=models.Index(fields=['documento', 'data_scadenza'], name='gf_scad_doc_data_idx'),
        ),
    ]
