# Generated by Django 5.2.13 on 2026-09-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0011_fic_import_period_and_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattureincloudconnessione',
            name='data_fine_import',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fattureincloudconnessione',
            name='periodo_import',
            field=models.CharField(choices=[('1', '1 mese'), ('3', '3 mesi'), ('6', '6 mesi'), ('9', '9 mesi'), ('12', 'Un anno'), ('tutte', 'Tutte'), ('manuale', 'Intervallo manuale')], default='tutte', max_length=10),
        ),
    ]
