# Generated by Django 5.2.13 on 2026-09-06 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0012_fic_import_date_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofornitore',
            name='proforma_origine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fattura_definitiva', to='gestione_finanziaria.documentofornitore'),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='riferimento_ordine',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='verifica_proforma',
            field=models.CharField(blank=True, choices=[('da_verificare', 'Da verificare'), ('distinta', 'Fattura distinta'), ('collegata', 'Collegata a pro-forma'), ('sostituita', 'Fattura definitiva ricevuta')], db_index=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='CollegamentoProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatico', models.BooleanField(default=False)),
                ('creato_at', models.DateTimeField(auto_now_add=True)),
                ('annullato_at', models.DateTimeField(blank=True, null=True)),
                ('dati_originali', models.JSONField(default=dict)),
                ('annullato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storico_proforma', to='gestione_finanziaria.documentofornitore')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storico_fatture_definitive', to='gestione_finanziaria.documentofornitore')),
            ],
            options={
                'ordering': ['-creato_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('annullato_at__isnull', True)), fields=('fattura',), name='gf_proforma_link_attivo')],
            },
        ),
    ]
