# Generated by Django 5.2.13 on 2026-04-27 20:09

import gestione_finanziaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0012_categoriaspesa_fornitore_documentofornitore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofornitore',
            name='allegato',
            field=models.FileField(blank=True, upload_to=gestione_finanziaria.models.documento_fornitore_upload_to),
        ),
    ]
