# Generated by Django 5.2.13 on 2026-04-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0013_alter_documentofornitore_allegato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofornitore',
            name='tipo_documento',
            field=models.CharField(choices=[('fattura', 'Fattura'), ('proforma', 'Proforma'), ('parcella', 'Parcella'), ('ricevuta', 'Ricevuta'), ('nota_credito', 'Nota di credito'), ('altro', 'Altro')], default='fattura', max_length=30),
        ),
    ]
