# Generated by Django 5.2.13 on 2026-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0014_alter_documentofornitore_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regolacategorizzazione',
            name='pattern',
            field=models.TextField(blank=True),
        ),
    ]
