# Generated by Django 5.2.13 on 2026-04-29 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0014_alter_iscrizione_gruppo_classe'),
        ('gestione_finanziaria', '0015_alter_regolacategorizzazione_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contobancario',
            name='tipo_conto',
            field=models.CharField(choices=[('conto_corrente', 'Conto corrente'), ('cassa_contanti', 'Cassa contanti'), ('carta_prepagata', 'Carta prepagata'), ('carta_credito', 'Carta di credito'), ('altro', 'Altro')], default='conto_corrente', help_text='Distingue conti bancari reali, cassa contanti, carte o altri saldi interni.', max_length=30),
        ),
        migrations.AddField(
            model_name='movimentofinanziario',
            name='canale',
            field=models.CharField(choices=[('banca', 'Banca'), ('contanti', 'Contanti'), ('personale', 'Spesa sostenuta da terzi'), ('carta', 'Carta'), ('prepagata', 'Prepagata'), ('altro', 'Altro')], db_index=True, default='banca', help_text='Canale operativo: banca, contanti, carta/prepagata o spesa sostenuta da terzi.', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentofinanziario',
            name='rimborsabile',
            field=models.BooleanField(default=False, help_text="True se la spesa sostenuta da terzi dovra' essere rimborsata."),
        ),
        migrations.AddField(
            model_name='movimentofinanziario',
            name='sostenitore',
            field=models.CharField(blank=True, help_text='Persona o soggetto che ha sostenuto la spesa, se diversa dalla scuola.', max_length=160),
        ),
        migrations.AddField(
            model_name='movimentofinanziario',
            name='sostenuta_da_terzi',
            field=models.BooleanField(default=False, help_text='True per spese sostenute da soci/genitori senza uscita dal conto della scuola.'),
        ),
        migrations.AddField(
            model_name='saldoconto',
            name='aggiornato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldi_conto_aggiornati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saldoconto',
            name='creato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldi_conto_creati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saldoconto',
            name='data_aggiornamento',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saldoconto',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contobancario',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conti', to='gestione_finanziaria.providerbancario'),
        ),
        migrations.AddIndex(
            model_name='movimentofinanziario',
            index=models.Index(fields=['canale', 'data_contabile'], name='gf_mov_canale_data_idx'),
        ),
    ]
