# Generated by Django 5.2.13 on 2026-09-13 22:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def queue_existing(apps, schema_editor):
    alias = schema_editor.connection.alias
    State = apps.get_model("gestione_finanziaria", "StatoAnalisiRiconciliazione")
    Job = apps.get_model("gestione_finanziaria", "RichiestaAnalisiRiconciliazione")
    Movement = apps.get_model("gestione_finanziaria", "MovimentoFinanziario")
    State.objects.using(alias).get_or_create(pk=1)
    batch = []
    for pk in Movement.objects.using(alias).exclude(stato_riconciliazione="ignorato").values_list("pk", flat=True).iterator(chunk_size=500):
        batch.append(Job(tipo="movimento", oggetto_id=pk))
        if len(batch) == 500:
            Job.objects.using(alias).bulk_create(batch, ignore_conflicts=True)
            batch = []
    Job.objects.using(alias).bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0015_documentofornitore_righe_importo_personalizzate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatoAnalisiRiconciliazione',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropostaRiconciliazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=64, unique=True)),
                ('abbinamento', models.CharField(db_index=True, max_length=64)),
                ('caso', models.CharField(db_index=True, max_length=80)),
                ('ambito', models.CharField(choices=[('rate', 'Rette'), ('fornitore', 'Fornitori')], max_length=16)),
                ('stato', models.CharField(choices=[('aperta', 'Da verificare'), ('confermata', 'Confermata'), ('rifiutata', 'Rifiutata'), ('superata', 'Da aggiornare')], db_index=True, default='aperta', max_length=16)),
                ('compatibilita', models.PositiveSmallIntegerField(default=0)),
                ('motivazioni', models.JSONField(default=list)),
                ('allocazioni', models.JSONField(default=list)),
                ('dati_verifica', models.JSONField(default=dict)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-compatibilita', '-id'],
                'indexes': [models.Index(fields=['stato', 'ambito', 'caso'], name='gf_proposta_casi_idx')],
            },
        ),
        migrations.CreateModel(
            name='DecisionePropostaRiconciliazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(max_length=16)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('dettaglio', models.TextField(blank=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisioni', to='gestione_finanziaria.propostariconciliazione')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RichiestaAnalisiRiconciliazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('oggetto_id', models.PositiveBigIntegerField()),
                ('richiesta_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('riprova_il', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tentativi', models.PositiveIntegerField(default=0)),
                ('errore', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo', 'oggetto_id'), name='gf_analisi_oggetto_unique')],
            },
        ),
        migrations.RunPython(queue_existing, migrations.RunPython.noop),
    ]
