# Generated by Django 5.2.13 on 2026-05-01 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0014_alter_iscrizione_gruppo_classe'),
        ('gestione_finanziaria', '0016_contobancario_tipo_conto_movimentofinanziario_canale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiconciliazioneRataMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riconciliazioni_rate_movimenti_create', to=settings.AUTH_USER_MODEL)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riconciliazioni_rate', to='gestione_finanziaria.movimentofinanziario')),
                ('rata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riconciliazioni_movimenti', to='economia.rataiscrizione')),
            ],
            options={
                'verbose_name': 'Riconciliazione rata movimento',
                'verbose_name_plural': 'Riconciliazioni rate movimenti',
                'db_table': 'gestione_finanziaria_riconciliazione_rata_movimento',
                'ordering': ['-data_creazione', '-id'],
                'indexes': [models.Index(fields=['movimento'], name='gf_ric_rata_mov_idx'), models.Index(fields=['rata'], name='gf_ric_rata_rata_idx')],
                'constraints': [models.UniqueConstraint(fields=('movimento', 'rata'), name='gf_ric_rata_mov_unique'), models.CheckConstraint(condition=models.Q(('importo__gt', 0)), name='gf_ric_rata_mov_importo_pos')],
            },
        ),
    ]
