# Generated by Django 5.2.13 on 2026-05-02 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0017_riconciliazioneratamovimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FattureInCloudConnessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Fatture in Cloud', max_length=150)),
                ('company_id', models.PositiveIntegerField(blank=True, help_text='ID azienda Fatture in Cloud.', null=True)),
                ('client_id', models.CharField(blank=True, max_length=160)),
                ('client_secret_cifrato', models.TextField(blank=True)),
                ('access_token_cifrato', models.TextField(blank=True)),
                ('refresh_token_cifrato', models.TextField(blank=True)),
                ('token_scadenza', models.DateTimeField(blank=True, null=True)),
                ('redirect_uri', models.URLField(blank=True)),
                ('base_url', models.URLField(default='https://api-v2.fattureincloud.it')),
                ('stato', models.CharField(choices=[('da_configurare', 'Da configurare'), ('attiva', 'Attiva'), ('errore', 'In errore')], default='da_configurare', max_length=20)),
                ('attiva', models.BooleanField(default=True)),
                ('sincronizza_documenti_registrati', models.BooleanField(default=True)),
                ('sincronizza_documenti_da_registrare', models.BooleanField(default=True)),
                ('ultimo_sync_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_esito', models.CharField(blank=True, choices=[('ok', 'Completata'), ('parziale', 'Parziale'), ('errore', 'Errore')], max_length=20)),
                ('ultimo_messaggio', models.TextField(blank=True)),
                ('oauth_state', models.CharField(blank=True, max_length=120)),
                ('webhook_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connessione Fatture in Cloud',
                'verbose_name_plural': 'Connessioni Fatture in Cloud',
                'db_table': 'gestione_finanziaria_fic_connessione',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FattureInCloudSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operazione', models.CharField(choices=[('completa', 'Sincronizzazione completa'), ('documento', 'Singolo documento'), ('webhook', 'Webhook')], default='completa', max_length=20)),
                ('esito', models.CharField(choices=[('ok', 'Completata'), ('parziale', 'Parziale'), ('errore', 'Errore')], default='ok', max_length=10)),
                ('documenti_creati', models.PositiveIntegerField(default=0)),
                ('documenti_aggiornati', models.PositiveIntegerField(default=0)),
                ('scadenze_create', models.PositiveIntegerField(default=0)),
                ('notifiche_create', models.PositiveIntegerField(default=0)),
                ('durata_millisecondi', models.PositiveIntegerField(blank=True, null=True)),
                ('messaggio', models.TextField(blank=True)),
                ('data_operazione', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log sincronizzazione Fatture in Cloud',
                'verbose_name_plural': 'Log sincronizzazioni Fatture in Cloud',
                'db_table': 'gestione_finanziaria_fic_sync_log',
                'ordering': ['-data_operazione', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificaFinanziaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=180)),
                ('messaggio', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('fattura_ricevuta', 'Fattura ricevuta'), ('scadenza_prossima', 'Scadenza prossima'), ('scadenza_insoluta', 'Scadenza insoluta'), ('riconciliazione', 'Riconciliazione'), ('integrazione', 'Integrazione')], default='integrazione', max_length=30)),
                ('livello', models.CharField(choices=[('info', 'Informazione'), ('warning', 'Attenzione'), ('errore', 'Errore')], default='info', max_length=20)),
                ('richiede_gestione', models.BooleanField(default=False, help_text="Se attivo, la notifica e' visibile solo agli utenti con gestione finanziaria.")),
                ('url', models.CharField(blank=True, max_length=300)),
                ('chiave_deduplica', models.CharField(blank=True, db_index=True, max_length=180)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('data_creazione', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Notifica finanziaria',
                'verbose_name_plural': 'Notifiche finanziarie',
                'db_table': 'gestione_finanziaria_notifica',
                'ordering': ['-data_creazione', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificaFinanziariaLettura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letta_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lettura notifica finanziaria',
                'verbose_name_plural': 'Letture notifiche finanziarie',
                'db_table': 'gestione_finanziaria_notifica_lettura',
                'ordering': ['-letta_il'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(db_index=True)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo', models.CharField(choices=[('banca', 'Movimento bancario'), ('manuale', 'Registrazione manuale'), ('contanti', 'Contanti'), ('carta', 'Carta'), ('altro', 'Altro')], default='manuale', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagamento fornitore',
                'verbose_name_plural': 'Pagamenti fornitori',
                'db_table': 'gestione_finanziaria_pagamento_fornitore',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='external_source',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='external_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='importato_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentofornitore',
            name='origine',
            field=models.CharField(choices=[('manuale', 'Inserimento manuale'), ('fatture_in_cloud', 'Fatture in Cloud')], db_index=True, default='manuale', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='documentofornitore',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('external_source', 'external_id'), name='gf_doc_forn_unique_external'),
        ),
        migrations.AddField(
            model_name='fattureincloudsynclog',
            name='connessione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_sincronizzazioni', to='gestione_finanziaria.fattureincloudconnessione'),
        ),
        migrations.AddField(
            model_name='notificafinanziaria',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='gestione_finanziaria.documentofornitore'),
        ),
        migrations.AddField(
            model_name='notificafinanziaria',
            name='movimento_finanziario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_fornitori', to='gestione_finanziaria.movimentofinanziario'),
        ),
        migrations.AddField(
            model_name='notificafinanziaria',
            name='scadenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='gestione_finanziaria.scadenzapagamentofornitore'),
        ),
        migrations.AddField(
            model_name='notificafinanziarialettura',
            name='notifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture', to='gestione_finanziaria.notificafinanziaria'),
        ),
        migrations.AddField(
            model_name='notificafinanziarialettura',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche_finanziarie_lette', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamentofornitore',
            name='conto_bancario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamenti_fornitori', to='gestione_finanziaria.contobancario'),
        ),
        migrations.AddField(
            model_name='pagamentofornitore',
            name='creato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamenti_fornitori_creati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamentofornitore',
            name='movimento_finanziario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamenti_fornitori', to='gestione_finanziaria.movimentofinanziario'),
        ),
        migrations.AddField(
            model_name='pagamentofornitore',
            name='scadenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='gestione_finanziaria.scadenzapagamentofornitore'),
        ),
        migrations.AddConstraint(
            model_name='notificafinanziaria',
            constraint=models.UniqueConstraint(condition=models.Q(('chiave_deduplica', ''), _negated=True), fields=('chiave_deduplica',), name='gf_notifica_unique_dedup'),
        ),
        migrations.AddConstraint(
            model_name='notificafinanziarialettura',
            constraint=models.UniqueConstraint(fields=('notifica', 'user'), name='gf_notifica_lettura_unique'),
        ),
        migrations.AddIndex(
            model_name='pagamentofornitore',
            index=models.Index(fields=['scadenza', 'data_pagamento'], name='gf_pag_forn_scad_data_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentofornitore',
            index=models.Index(fields=['movimento_finanziario'], name='gf_pag_forn_mov_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagamentofornitore',
            constraint=models.CheckConstraint(condition=models.Q(('importo__gt', 0)), name='gf_pag_forn_importo_pos'),
        ),
        migrations.AddConstraint(
            model_name='pagamentofornitore',
            constraint=models.UniqueConstraint(condition=models.Q(('movimento_finanziario__isnull', False)), fields=('scadenza', 'movimento_finanziario'), name='gf_pag_forn_unique_scad_mov'),
        ),
    ]
