# Generated by Django 5.2.13 on 2026-09-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0017_refresh_tuition_proposals'),
        ('servizi_extra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiconciliazioneServizioExtraMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riconciliazioni_servizi_extra', to='gestione_finanziaria.movimentofinanziario')),
                ('rata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riconciliazioni_movimenti', to='servizi_extra.rataservizioextra')),
            ],
            options={
                'verbose_name': 'Riconciliazione servizio extra movimento',
                'verbose_name_plural': 'Riconciliazioni servizi extra movimenti',
                'ordering': ['-data_creazione', '-id'],
                'constraints': [models.UniqueConstraint(fields=('movimento', 'rata'), name='gf_ric_extra_mov_unique'), models.CheckConstraint(condition=models.Q(('importo__gt', 0)), name='gf_ric_extra_importo_pos')],
            },
        ),
    ]
