# Generated by Django 5.2.13 on 2026-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0018_fattureincloudconnessione_fattureincloudsynclog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattureincloudconnessione',
            name='avviato_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fattureincloudconnessione',
            name='in_corso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fattureincloudconnessione',
            name='intervallo_sync_ore',
            field=models.PositiveIntegerField(default=6, help_text='Ogni quante ore tentare la sincronizzazione automatica.'),
        ),
        migrations.AddField(
            model_name='fattureincloudconnessione',
            name='sync_automatico',
            field=models.BooleanField(default=False, help_text='Se attivo, Arboris prova a sincronizzare periodicamente questa connessione.'),
        ),
    ]
