# Generated by Django 5.2.13 on 2026-05-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_finanziaria', '0021_unifica_categorie_spesa_finanziarie'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoceBudgetRicorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata'), ('uscita', 'Uscita')], default='uscita', max_length=20)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequenza', models.CharField(choices=[('una_tantum', 'Una tantum'), ('mensile', 'Mensile'), ('bimestrale', 'Bimestrale'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale')], default='mensile', max_length=20)),
                ('data_inizio', models.DateField(db_index=True)),
                ('data_fine', models.DateField(blank=True, db_index=True, null=True)),
                ('giorno_previsto', models.PositiveSmallIntegerField(default=1)),
                ('mese_previsto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voci_budget', to='gestione_finanziaria.categoriafinanziaria')),
                ('fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_budget', to='gestione_finanziaria.fornitore')),
            ],
            options={
                'verbose_name': 'Voce budget ricorrente',
                'verbose_name_plural': 'Voci budget ricorrenti',
                'db_table': 'gestione_finanziaria_voce_budget_ricorrente',
                'ordering': ['tipo', 'categoria__nome', 'nome'],
                'indexes': [models.Index(fields=['tipo', 'attiva'], name='gf_budget_tipo_attiva_idx'), models.Index(fields=['data_inizio', 'data_fine'], name='gf_budget_periodo_idx')],
            },
        ),
    ]
