# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsservazioneStudente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titolo')),
                ('data_inserimento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data inserimento')),
                ('testo', models.TextField(verbose_name='Testo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('aggiornato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osservazioni_studenti_update', to=settings.AUTH_USER_MODEL, verbose_name='Aggiornato da')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osservazioni_studenti_create', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osservazioni', to='anagrafica.studente', verbose_name='Studente')),
            ],
            options={
                'verbose_name': 'Osservazione studente',
                'verbose_name_plural': 'Osservazioni studenti',
                'db_table': 'osservazioni_osservazione_studente',
                'ordering': ['data_inserimento', 'id'],
                'indexes': [models.Index(fields=['studente', 'data_inserimento', 'id'], name='osservazioni_stud_data_idx')],
            },
        ),
    ]
