"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import dj_database_url
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    raw_value = os.environ.get(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-sg+t9@_ej5r58z(c@aji3-ddce#zr6_nh5uderw6xsm)k63ln)'
SECRET_KEY = '1+f0hexzqb_3t%ps51)re9wc7%0&&(pe!)=#*2v2yjyh^%9!-v'

# SECURITY WARNING: don't run with debug turned on in production!
HAS_DATABASE_URL = bool(os.environ.get("DATABASE_URL"))
DEBUG = env_bool("DEBUG", default=not HAS_DATABASE_URL)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anagrafica',
    'sistema',
    'scuola',
    'calendario',
    'economia',
    'fondo_accantonamento.apps.FondoAccantonamentoConfig',
    'servizi_extra',
    'gestione_finanziaria',
    'gestione_amministrativa.apps.GestioneAmministrativaConfig',
]

USE_S3_MEDIA = env_bool("USE_S3_MEDIA") or bool(os.environ.get("AWS_STORAGE_BUCKET_NAME", "").strip())
if USE_S3_MEDIA:
    INSTALLED_APPS.append("storages")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'sistema.middleware.AuditUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'sistema.middleware.DatabaseBackupScheduleMiddleware',
    'gestione_finanziaria.middleware.SincronizzazionePsd2ScheduleMiddleware',
]

ROOT_URLCONF = 'arboris.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sistema.context_processors.scuola_context',
                'sistema.context_processors.general_settings_context',
                'sistema.context_processors.sistema_permissions_context',
                'sistema.context_processors.arboris_popup_manifest_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'arboris.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Stringa di collegamento al database arboris_dev, database per lo sviluppo
if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "arboris_dev",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True

#Imposto il formato di data e ora in italiano (giorno/mese/anno)
DATE_FORMAT = "d/m/Y"
DATETIME_FORMAT = "d/m/Y H:i"
SHORT_DATE_FORMAT = "d/m/Y"

DATE_INPUT_FORMATS = ['%d/%m/%Y']
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG or "test" in sys.argv
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

#Aggiungo la regola per i file da caricare nella cartella media
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / "media"))
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
DATABASE_BACKUPS_UPLOAD_PREFIX = os.environ.get("DATABASE_BACKUPS_UPLOAD_PREFIX", "db_backups").strip().strip("/") or "db_backups"
DATABASE_RESTORE_UPLOAD_PREFIX = os.environ.get("DATABASE_RESTORE_UPLOAD_PREFIX", "db_restore_uploads").strip().strip("/") or "db_restore_uploads"

if USE_S3_MEDIA:
    aws_storage_bucket_name = os.environ.get("AWS_STORAGE_BUCKET_NAME", "").strip()
    if not aws_storage_bucket_name:
        raise ImproperlyConfigured(
            "USE_S3_MEDIA e' attivo ma AWS_STORAGE_BUCKET_NAME non e' configurato."
        )

    aws_s3_region_name = os.environ.get("AWS_S3_REGION_NAME", "").strip() or None
    aws_s3_endpoint_url = os.environ.get("AWS_S3_ENDPOINT_URL", "").strip() or None
    aws_s3_custom_domain = os.environ.get("AWS_S3_CUSTOM_DOMAIN", "").strip() or None
    aws_media_location = os.environ.get("AWS_MEDIA_LOCATION", "").strip()

    s3_default_storage_options = {
        "bucket_name": aws_storage_bucket_name,
        "region_name": aws_s3_region_name,
        "access_key": os.environ.get("AWS_ACCESS_KEY_ID", "").strip() or None,
        "secret_key": os.environ.get("AWS_SECRET_ACCESS_KEY", "").strip() or None,
        "default_acl": None,
        "file_overwrite": env_bool("AWS_S3_FILE_OVERWRITE", default=False),
        "querystring_auth": env_bool("AWS_QUERYSTRING_AUTH", default=True),
        "signature_version": os.environ.get("AWS_S3_SIGNATURE_VERSION", "s3v4").strip() or "s3v4",
    }

    if aws_s3_endpoint_url:
        s3_default_storage_options["endpoint_url"] = aws_s3_endpoint_url
    if aws_s3_custom_domain:
        s3_default_storage_options["custom_domain"] = aws_s3_custom_domain
    if aws_media_location:
        s3_default_storage_options["location"] = aws_media_location

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": s3_default_storage_options,
    }

# Celery (ripristino database in background). Se CELERY_BROKER_URL è vuoto, si usa un thread worker-side.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "").strip()
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", CELERY_BROKER_URL).strip() or CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
# Evita attese infinite su code non raggiungibili in sviluppo
if CELERY_BROKER_URL:
    CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
