# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_classe', models.CharField(max_length=100)),
                ('sezione_classe', models.CharField(blank=True, max_length=20)),
                ('ordine_classe', models.PositiveIntegerField()),
                ('attiva', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classi',
                'db_table': 'scuola_classe',
                'ordering': ['ordine_classe', 'nome_classe', 'sezione_classe'],
            },
        ),
        migrations.CreateModel(
            name='AnnoScolastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_anno_scolastico', models.CharField(max_length=50, unique=True)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField()),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Anno scolastico',
                'verbose_name_plural': 'Anni scolastici',
                'db_table': 'scuola_anno_scolastico',
                'ordering': ['-data_inizio', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fine__gte', models.F('data_inizio'))), name='scuola_anno_data_fine_gte_data_inizio')],
            },
        ),
        migrations.CreateModel(
            name='GruppoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gruppo_classe', models.CharField(max_length=150)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gruppi_classe', to='scuola.annoscolastico')),
                ('classi', models.ManyToManyField(related_name='gruppi_classe', to='scuola.classe', verbose_name='Classi incluse')),
            ],
            options={
                'verbose_name': 'Pluriclasse',
                'verbose_name_plural': 'Pluriclassi',
                'db_table': 'scuola_gruppo_classe',
                'ordering': ['anno_scolastico__data_inizio', 'nome_gruppo_classe', 'id'],
                'constraints': [models.UniqueConstraint(fields=('anno_scolastico', 'nome_gruppo_classe'), name='unique_scuola_gruppo_classe_per_anno')],
            },
        ),
    ]
