# Generated by Django 5.2.13 on 2026-04-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scuola", "0002_eventocalendario"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="EventoCalendario",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE scuola_evento_calendario RENAME TO claendario_evento_calendario;",
                    reverse_sql="ALTER TABLE claendario_evento_calendario RENAME TO scuola_evento_calendario;",
                ),
            ],
        ),
    ]
