# Generated by Django 5.2.13 on 2026-04-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuola', '0003_extract_calendario_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annoscolastico',
            name='corrente',
        ),
        migrations.AddConstraint(
            model_name='annoscolastico',
            constraint=models.CheckConstraint(condition=models.Q(('data_fine__gte', models.F('data_inizio'))), name='scuola_anno_data_fine_gte_data_inizio'),
        ),
    ]
