# Generated by Django 5.2.13 on 2026-04-29 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuola', '0004_remove_annoscolastico_corrente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruppoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gruppo_classe', models.CharField(max_length=150)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('anno_scolastico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gruppi_classe', to='scuola.annoscolastico')),
                ('classi', models.ManyToManyField(related_name='gruppi_classe', to='scuola.classe', verbose_name='Classi incluse')),
            ],
            options={
                'verbose_name': 'Gruppo classe',
                'verbose_name_plural': 'Gruppi classe',
                'db_table': 'scuola_gruppo_classe',
                'ordering': ['anno_scolastico__data_inizio', 'nome_gruppo_classe', 'id'],
                'constraints': [models.UniqueConstraint(fields=('anno_scolastico', 'nome_gruppo_classe'), name='unique_scuola_gruppo_classe_per_anno')],
            },
        ),
    ]
