# Generated by Django 5.2.13 on 2026-04-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuola', '0005_gruppoclasse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['ordine_classe', 'nome_classe', 'sezione_classe'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classi'},
        ),
        migrations.AlterModelOptions(
            name='gruppoclasse',
            options={'ordering': ['anno_scolastico__data_inizio', 'nome_gruppo_classe', 'id'], 'verbose_name': 'Pluriclasse', 'verbose_name_plural': 'Pluriclassi'},
        ),
        migrations.RemoveConstraint(
            model_name='classe',
            name='unique_scuola_classe_per_anno',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='anno_scolastico',
        ),
    ]
