# Generated by Django 5.2.13 on 2026-05-10 11:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economia', '0001_initial'),
        ('scuola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoAccantonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sempre_attivo', models.BooleanField(default=False, help_text="Se attivo, il piano non e' vincolato a un singolo anno scolastico (es. conto comune a tutti gli anni).")),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('modalita', models.CharField(choices=[('solo_manuale', 'Solo versamenti e prelievi manuali'), ('percentuale_rette', 'Percentuale sulle rette'), ('versamenti_periodici', 'Versamenti periodici (date calcolate)'), ('misto', 'Percentuale sulle rette e Versamenti periodici')], default='solo_manuale', max_length=40)),
                ('percentuale_su_rette', models.DecimalField(blank=True, decimal_places=2, help_text="Usata se la modalita' include percentuale sulle rette. Conviene un solo piano attivo con percentuale per ogni contesto (anno o piano sempre attivo), altrimenti ne viene usato uno solo (il primo per nome).", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('periodicita', models.CharField(blank=True, choices=[('mensile', 'Mensile'), ('bimestrale', 'Bimestrale'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale')], max_length=20)),
                ('data_primo_versamento', models.DateField(blank=True, help_text='Data del primo versamento periodico atteso (base per le scadenze).', null=True)),
                ('importo_versamento_periodico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_deposito', models.CharField(choices=[('conto', 'Conto corrente'), ('contanti', 'Contanti'), ('paypal', 'PayPal o portafoglio elettronico'), ('altro', 'Altro')], default='altro', max_length=20)),
                ('descrizione_deposito', models.CharField(blank=True, help_text='Es. Nome banca, cassa, piattaforma.', max_length=255)),
                ('coordinate_riferimento', models.TextField(blank=True, help_text="IBAN, riferimenti o note per l'accesso. Trattare come informazioni sensibili.")),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('anno_scolastico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piani_fondo_accantonamento', to='scuola.annoscolastico')),
            ],
            options={
                'verbose_name': 'Piano di accantonamento',
                'verbose_name_plural': 'Piani di accantonamento',
                'db_table': 'fondo_accantonamento_piano',
                'ordering': ['-sempre_attivo', '-anno_scolastico__data_inizio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('versamento', 'Versamento in entrata'), ('prelievo', 'Prelievo o utilizzo in uscita'), ('sconto_retta', 'Sconto accantonamento su retta (economia)')], max_length=20)),
                ('data', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.TextField(blank=True)),
                ('richiedente', models.CharField(blank=True, help_text='Per prelievi: chi ha prelevato o approvato.', max_length=200)),
                ('motivo', models.TextField(blank=True, help_text='Per prelievi: motivazione.')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('rata_iscrizione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_fondo_accantonamento', to='economia.rataiscrizione')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='fondo_accantonamento.pianoaccantonamento')),
            ],
            options={
                'verbose_name': 'Movimento fondo',
                'verbose_name_plural': 'Movimenti fondo',
                'db_table': 'fondo_accantonamento_movimento',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegolaScontoAgevolazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mensilita', models.PositiveIntegerField(blank=True, help_text="Prime N rate mensili; lasciare vuoto per usare tutte le mensilita' del piano rate.", null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('agevolazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regola_sconto_fondo', to='economia.agevolazione')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regole_sconto_agevolazione', to='fondo_accantonamento.pianoaccantonamento')),
            ],
            options={
                'verbose_name': 'Regola sconto fondo (agevolazione)',
                'verbose_name_plural': 'Regole sconto fondo (agevolazioni)',
                'db_table': 'fondo_acc_regola_sconto_agev',
            },
        ),
        migrations.CreateModel(
            name='ScadenzaVersamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField()),
                ('importo_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stato', models.CharField(choices=[('pianificato', 'Pianificato'), ('soddisfatto', 'Soddisfatto (versamento registrato)'), ('annullato', 'Annullato')], default='pianificato', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('movimento_versamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scadenze_soddisfatte', to='fondo_accantonamento.movimentofondo')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='fondo_accantonamento.pianoaccantonamento')),
            ],
            options={
                'verbose_name': 'Scadenza versamento',
                'verbose_name_plural': 'Scadenze versamento',
                'db_table': 'fondo_accantonamento_scadenza',
                'ordering': ['data_scadenza', 'id'],
            },
        ),
        migrations.AddField(
            model_name='movimentofondo',
            name='scadenza_versamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_collegati', to='fondo_accantonamento.scadenzaversamento'),
        ),
        migrations.AddConstraint(
            model_name='pianoaccantonamento',
            constraint=models.UniqueConstraint(condition=models.Q(('anno_scolastico__isnull', False)), fields=('anno_scolastico', 'nome'), name='fondo_acc_piano_unico_anno_nome'),
        ),
        migrations.AddConstraint(
            model_name='pianoaccantonamento',
            constraint=models.UniqueConstraint(condition=models.Q(('sempre_attivo', True)), fields=('nome',), name='fondo_acc_piano_unico_nome_sempre_attivo'),
        ),
        migrations.AddIndex(
            model_name='scadenzaversamento',
            index=models.Index(fields=['piano', 'data_scadenza'], name='fondo_acc_scad_piano_data'),
        ),
        migrations.AddConstraint(
            model_name='scadenzaversamento',
            constraint=models.UniqueConstraint(fields=('piano', 'data_scadenza'), name='fondo_acc_scad_unica_data_per_piano'),
        ),
        migrations.AddIndex(
            model_name='movimentofondo',
            index=models.Index(fields=['piano', 'data'], name='fondo_acc_mov_piano_data'),
        ),
    ]
