# Generated by Django 5.2.13 on 2026-04-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0011_prestazionescambioretta'),
        ('fondo_accantonamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofondo',
            name='rata_iscrizione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimenti_fondo_accantonamento', to='economia.rataiscrizione'),
        ),
    ]
