# Generated by Django 5.2.13 on 2026-04-24 07:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0011_prestazionescambioretta'),
        ('fondo_accantonamento', '0002_alter_movimentofondo_rata_iscrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoaccantonamento',
            name='percentuale_su_rette',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Usata se la modalita' include percentuale sulle rette. Per anno scolastico conviene un solo piano attivo con percentuale, altrimenti ne viene usato uno solo (il primo per nome).", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.CreateModel(
            name='RegolaScontoAgevolazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mensilita', models.PositiveIntegerField(blank=True, help_text="Prime N rate mensili; lasciare vuoto per usare tutte le mensilita' del piano rate.", null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('agevolazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regola_sconto_fondo', to='economia.agevolazione')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regole_sconto_agevolazione', to='fondo_accantonamento.pianoaccantonamento')),
            ],
            options={
                'verbose_name': 'Regola sconto fondo (agevolazione)',
                'verbose_name_plural': 'Regole sconto fondo (agevolazioni)',
                'db_table': 'fondo_acc_regola_sconto_agev',
            },
        ),
    ]
