# Generated by Django 5.2.13 on 2026-04-24 07:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_accantonamento', '0003_alter_pianoaccantonamento_percentuale_su_rette_and_more'),
        ('scuola', '0003_extract_calendario_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pianoaccantonamento',
            options={'ordering': ['-sempre_attivo', '-anno_scolastico__data_inizio', 'nome'], 'verbose_name': 'Piano di accantonamento', 'verbose_name_plural': 'Piani di accantonamento'},
        ),
        migrations.RemoveConstraint(
            model_name='pianoaccantonamento',
            name='fondo_acc_piano_unico_per_anno_nome',
        ),
        migrations.AddField(
            model_name='pianoaccantonamento',
            name='sempre_attivo',
            field=models.BooleanField(default=False, help_text="Se attivo, il piano non e' vincolato a un singolo anno scolastico (es. conto comune a tutti gli anni)."),
        ),
        migrations.AlterField(
            model_name='pianoaccantonamento',
            name='anno_scolastico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piani_fondo_accantonamento', to='scuola.annoscolastico'),
        ),
        migrations.AlterField(
            model_name='pianoaccantonamento',
            name='percentuale_su_rette',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Usata se la modalita' include percentuale sulle rette. Conviene un solo piano attivo con percentuale per ogni contesto (anno o piano sempre attivo), altrimenti ne viene usato uno solo (il primo per nome).", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddConstraint(
            model_name='pianoaccantonamento',
            constraint=models.UniqueConstraint(condition=models.Q(('anno_scolastico__isnull', False)), fields=('anno_scolastico', 'nome'), name='fondo_acc_piano_unico_anno_nome'),
        ),
        migrations.AddConstraint(
            model_name='pianoaccantonamento',
            constraint=models.UniqueConstraint(condition=models.Q(('sempre_attivo', True)), fields=('nome',), name='fondo_acc_piano_unico_nome_sempre_attivo'),
        ),
    ]
