# Generated by Django 5.2.13 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fondo_accantonamento", "0004_alter_pianoaccantonamento_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pianoaccantonamento",
            name="modalita",
            field=models.CharField(
                choices=[
                    ("solo_manuale", "Solo versamenti e prelievi manuali"),
                    ("percentuale_rette", "Percentuale sulle rette"),
                    ("versamenti_periodici", "Versamenti periodici (date calcolate)"),
                    ("misto", "Percentuale sulle rette e Versamenti periodici"),
                ],
                default="solo_manuale",
                max_length=40,
            ),
        ),
    ]
